### ISSUE TITLE
How to build Android library with GPU delegate?

### ISSUE THREAD

**Issue by applikationsprogramvara** [am15h/tflite_flutter_plugin#103]
I have stability issues with running my model on Android with GPU delegate.

So I thought I can rebuild the library from scratch and thy the most fresh one, but I can't figure out how to do it.

Actually I need to build the library, that you uploaded [here](https://github.com/am15h/tflite_flutter_plugin/releases/tag/v0.5.0). I would like to build `libtensorflowlite_c_arm64_delegate.so` for the beginning.

I tried to build TensorFlow with different parameters. The most successful was this one, which I found [here](https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/lite/experimental/examples/unity/TensorFlowLitePlugin/README.md):
`bazel build -c opt --config=android_arm64 //tensorflow/lite/c:tensorflowlite_c`
I've got the library `libtensorflowlite_c.so` for arm64 without GPU delegate and it is working.

How to build Android library with GPU delegate?

**Comment by applikationsprogramvara** [comment]
Ok. I've managed to build the Android library with usual TensorFlow and GPU together. It looks like you are using some custom build instructions to archive that.

# Building

I added the following lines at the end of [this file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/BUILD)

``` bazel
tflite_jni_binary(
    name = "libtensorflowlite_jni_normal_with_gpu.so", # <-- the new name here
    linkscript = ":tflite_version_script.lds",
    deps = [
        "//tensorflow/lite/c:c_api",
        "//tensorflow/lite/c:c_api_experimental",
        "//tensorflow/lite/delegates/nnapi/java/src/main/native",
        "//tensorflow/lite/delegates/xnnpack:xnnpack_delegate",
        "//tensorflow/lite/java/src/main/native",
        "//tensorflow/lite/delegates/gpu/java/src/main/native", # <-- this line was added
    ],
)

```

Then I started the command
`bazel build -c opt --config=android_arm64 //tensorflow/lite/java:libtensorflowlite_jni_normal_with_gpu.so`

# Check

I've checked the symbols using this command:
`nm -gDC libtensorflowlite_jni_normal_with_gpu.so`

All the required symbols are present: the usual options `TfLiteInterpreterOptionsCreate` as well as the delegate one `TfLiteGpuDelegateV2Create`.

# Conclusion

- It looks like my app is working and much more stable, so I think I did it right
- It makes sense to add these notes to Readme or to Wiki
- One another idea is instead of using local precompiled so-libraries to use standard libraries Maven as mentioned [here](https://www.tensorflow.org/lite/performance/gpu#android_with_android_studio):
``` gradle
dependencies {
    implementation 'org.tensorflow:tensorflow-lite:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.3.0'
}
```
What do you think?

**Comment by am15h** [comment]
Thanks a lot @applikationsprogramvara for sharing this guide and your interests in project.  The idea of using maven libraries is great.  I have tested it locally for android and I think we should include it in the package. Have you tested [this on iOS](https://www.tensorflow.org/lite/performance/gpu#ios_with_xcode) too?

**Comment by applikationsprogramvara** [comment]
@am15h nope. I was not lucky to start [this example](https://www.tensorflow.org/lite/performance/gpu#ios_with_xcode). All my attempts ended up with errors.

**Comment by am15h** [comment]
Hi @applikationsprogramvara, I have added this tutorial in wiki, https://github.com/am15h/tflite_flutter_plugin/wiki/Build-android-binaries-with-GPU-delegate. Please review it and make edits if required. Also as we are discussing binary placing in this thread https://github.com/am15h/tflite_flutter_plugin/issues/110, I am closing this issue. Thanks a lot for your contribution.
