### ISSUE TITLE
Enable quantization flag

### ISSUE THREAD

**Issue by applikationsprogramvara** [am15h/tflite_flutter_plugin#109]
In the last version of TFLite there is an `Enable quantization`  flag which allow you to use GPU delegate for quantized models.
Otherwise you end up loading model as without GPU delegate (at least from my experiments). 

Here are the links to the TFLite:
- For Android [here](https://github.com/tensorflow/tensorflow/blob/be19b15ed5559ac92b527728c4c04d5eb3bd5984/tensorflow/lite/delegates/gpu/delegate.h#L55) and [here](https://github.com/tensorflow/tensorflow/blob/be19b15ed5559ac92b527728c4c04d5eb3bd5984/tensorflow/lite/delegates/gpu/delegate.h#L98) and
- For iOS [here](https://github.com/tensorflow/tensorflow/blob/be19b15ed5559ac92b527728c4c04d5eb3bd5984/tensorflow/lite/delegates/gpu/metal_delegate.h#L50)

Actually I already experimented with it and it kinda working:
You can take a look into this commit https://github.com/applikationsprogramvara/tflite_flutter_plugin/commit/11f81946c17ae5c5bf6361a64b13b94abeaf11ac
Though I am not sure how it will work with the previous versions, where the quantization flag is still missing. 

You can consider to add the code to the main branch.

**Comment by am15h** [comment]
Thanks @applikationsprogramvara, Would you like to make a PR for this?
