### ISSUE TITLE
Extracting Weight, Biases and Inverse_Weights

### ISSUE THREAD

**Issue by amul-dhungel** [am15h/tflite_flutter_plugin#113]
Hello, I am currently trying to extract weight, baises and inverse_weights from the tflite mode. And I get this type of out put format
![image](https://user-images.githubusercontent.com/51743296/116788769-4d7c3200-aacb-11eb-9fec-76de37ae08b4.png)

Instead I want to output in this format.
![image](https://user-images.githubusercontent.com/51743296/116788806-756b9580-aacb-11eb-9390-1b00ebdb0f6e.png)

These are the same weights and biases extracted from the tflite model, which was used in flutter.

**Comment by am15h** [comment]
Extracting data from intermediate layers is not possible with tflite.
