### ISSUE TITLE
Using NNapi on android has a delay for first inference

### ISSUE THREAD

**Issue by CaptainDario** [am15h/tflite_flutter_plugin#114]
When I am using this plugin on android I am getting a pretty big delay when I enable NnApi.
Creating the interpreter like this:
``` dart
interpreterOptions = InterpreterOptions()..useNnApiForAndroid = true;
interpreter = await Interpreter.fromAsset(
  _assetPath,
  options: interpreterOptions
);
```
leads to a delay of 1-2s. But only for the first inference. 
Coming calls to the interpreter are not affected.

When creating a interpreter to use the CPU like this:
``` dart
interpreter = await Interpreter.fromAsset(_assetPath);
```
there is no such delay.
My current model is not big and there is no difference (in time) for using CPU / GPU / NNAPI.
Therefore I am not too concerned about it. However I am curious for why this is the case and how this could be prevented?

**Comment by am15h** [comment]
Thanks @CaptainDario, for reporting this. I will investigate.

**Comment by CaptainDario** [comment]
If you need additional information let me know.
I am testing NNAPI on a LG V40 ThinQ with Android 10.

**Comment by CaptainDario** [comment]
After updating all packages, flutter and dart this seems to be solved.
