### ISSUE TITLE
Update TF Lite binaries and broken link

### ISSUE THREAD

**Issue by CaptainDario** [am15h/tflite_flutter_plugin#124]
Now where TF Lite 2.5.0 is out, it would be nice to be able use this version.
Can problems arise when I want to use a model created in TF 2.5.0 with this package (this package uses TF Lite 2.4.1 I Guess)?

Also the link in the README on how to build custom TF Lite versions is broken.
Here: 
>These scripts install pre-built binaries based on latest stable tensorflow release. For info about using other tensorflow versions refer to this part of readme.

**Comment by WillianSalceda** [comment]
Bump!

**Comment by am15h** [comment]
Thanks for notifying. I have updated the readme. I will also build the binaries for version 2.5.0 and publish them.

**Comment by WillianSalceda** [comment]
@am15h Any prediction of when you'll build the 2.5.0 binaries and publish them?

Thanks in advance.

**Comment by am15h** [comment]
Hi @WillianSalceda, the latest binaries are now published at https://github.com/am15h/tflite_flutter_plugin/releases/tag/tf_2.5

**Comment by CaptainDario** [comment]
@am15h can the new version installed by changing the [tag](https://github.com/am15h/tflite_flutter_plugin/blob/51cc5ce538de637685b037e5668274f37edfbd88/install.bat#L7) in the install script?

**Comment by am15h** [comment]
I have now updated the scripts to just change [TfLite Version](https://github.com/am15h/tflite_flutter_plugin/blob/master/install.sh#L8) and download corresponding binaries.
