### ISSUE TITLE
Using tflite with tflite_flutter package make conflict with tensorflowliteC.framework

### ISSUE THREAD

**Issue by AhmedMahhmoud** [am15h/tflite_flutter_plugin#134]
Using tflite with tflite_flutter package make conflict with tensorflowliteC.framework how can i fix it  as i need both packages?  
or someone tell me how can i use applyModelOnimage function from tflite to tflite_flutter

**Comment by am15h** [comment]
I was unable to find any solution for this issue on the internet. The only way people seem to be solving this is by remove one of the packages.

As far as your use case is concerned, I think it would be sufficient for you to just use tflite_flutter and drop tflite package, as tflite_flutter offers a much larger set of features. You may want to refer to examples as well. https://github.com/am15h/tflite_flutter_plugin#examples

**Comment by AhmedMahhmoud** [comment]
> I was unable to find any solution for this issue on the internet. The only way people seem to be solving this is by remove one of the packages.
> 
> As far as your use case is concerned, I think it would be sufficient for you to just use tflite_flutter and drop tflite package, as tflite_flutter offers a much larger set of features. You may want to refer to examples as well. https://github.com/am15h/tflite_flutter_plugin#examples

Hello thanks for reply ,I want to drop the tflite package indeed but If you can help me please, i have a model which contains the labels (only two labels )and the data ,
i tried to do like the Image Classification App in the example but here what i get when i try to call interpreter.run :
Bad state: failed precondition and yes i already checked issue #29 but wasn't able to solve the problem .
