### ISSUE TITLE
Error in loading a model with certain OPs

### ISSUE THREAD

**Issue by Sid911** [am15h/tflite_flutter_plugin#149]
Hi, I tried to load my custom model which gives an error
```log
E/tflite  (22505): Didn't find op for builtin opcode 'ADD' version '4'. An older version of this builtin might be supported. Are you using an old TFLite binary with a newer model?
E/tflite  (22505): Registration failed.
E/flutter (22505): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Unable to create interpreter.
E/flutter (22505): #0      checkArgument (package:quiver/check.dart:45:5)
E/flutter (22505): #1      new Interpreter._create (package:tflite_flutter/src/interpreter.dart:43:5)
E/flutter (22505): #2      new Interpreter.fromBuffer (package:tflite_flutter/src/interpreter.dart:94:37)
E/flutter (22505): #3      Interpreter.fromAsset (package:tflite_flutter/src/interpreter.dart:112:24)
E/flutter (22505): <asynchronous suspension>
E/flutter (22505): #4      _TestMLPageState.build.<anonymous closure> (package:summarize/classes/Homepage/TestMLPage.dart:34:41)
E/flutter (22505): <asynchronous suspension>
E/flutter (22505): 
```
Which tells me that there is some issue with the version of the OPs I am using. Currently my tflite conversion requires tensorflow ops `tf.lite.OpsSet.SELECT_TF_OPS`
The code is pretty straight forward.
```py
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = []
converter.target_spec.supported_ops.append(tf.lite.OpsSet.TFLITE_BUILTINS) 
converter.target_spec.supported_ops.append(tf.lite.OpsSet.SELECT_TF_OPS)
result = converter.convert()
```

I am also using the latest 2.5 Binaries so is there a way to make this work? or there is any option I could change that I haven't looked into, I am pretty new to testing out tflite so any help would be appreciated.

**Comment by TetrixGauss** [comment]
@Sid911  So what is the solution to this problem ? because i get the same thing!

**Comment by Sid911** [comment]
> @Sid911  So what is the solution to this problem ? because i get the same thing!
> 

To build your own binary... But that's another black hole because I could never get custom binary built for my model... 

Using Fat binary causes 70mb of binaries to be present which aren't required, also if you use binaries from maven they don't have gpu delegates. 
In the end I stopped working with flutter and moved to rust based solution as I wanted to support desktop first than mobile, I just didn't seem worth the hassle for future of my application's sake to go through so much trouble. Either way I was just experimenting around anyway that time. 

If you ever find a way, let me know.
