### ISSUE TITLE
Error running example: The method 'run' was called on null.

### ISSUE THREAD

**Issue by kame5** [am15h/tflite_flutter_plugin#15]
I try running your code in the example folder. APP can run  but It never classifies word and it never run Interpreter loaded successfully
>print('Interpreter loaded successfully');

**Comment by kame5** [comment]
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The method 'run' was called on null.
Receiver: null
Tried calling: run(Instance(length:1) of '_GrowableList', Instance(length:1) of '_GrowableList')

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Classifier.classify (package:tflite_flutter_plugin_example/classifier.dart:44:18)
#2      _MyAppState.build.<anonymous closure> (package:tflite_flutter_plugin_example/main.dart:60:54)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#fdf21
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(345.5, 643.8)
  finalLocalPosition: Offset(35.1, 15.3)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
this is an error when I try your classifier.

**Comment by am15h** [comment]
Hi @kame5, I think you have forgot to add the dynamic libraries for android, follow the [Initial setup section](https://github.com/am15h/tflite_flutter_plugin#initial-setup) in readme before running the app.

It says, 
Place [install.sh](https://github.com/am15h/tflite_flutter_plugin/blob/master/install.sh) at root of your project and execute the command `sh install.sh`.

Also, you must be getting this error as well (you didn't include in the log provided above ) indicating the absence of dynamic library.
```
E/flutter ( 4348): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libtensorflowlite_c.so" not found)
[        ] E/flutter ( 4348): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
[        ] E/flutter ( 4348): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
[        ] E/flutter ( 4348): #2      tflitelib.<anonymous closure> (package:tflite_flutter/src/bindings/dlib.dart:8:27)
[        ] E/flutter ( 4348): #3      tflitelib (package:tflite_flutter/src/bindings/dlib.dart:12:2)
[        ] E/flutter ( 4348): #4      tflitelib (package:tflite_flutter/src/bindings/dlib.dart:6:16)
[        ] E/flutter ( 4348): #5      tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart:10:35)
[        ] E/flutter ( 4348): #6      tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart:10:5)
[        ] E/flutter ( 4348): #7      new Model.fromBuffer (package:tflite_flutter/src/model.dart:36:19)
[        ] E/flutter ( 4348): #8      new Interpreter.fromBuffer (package:tflite_flutter/src/interpreter.dart:49:25)
[        ] E/flutter ( 4348): #9      Interpreter.fromAsset (package:tflite_flutter/src/interpreter.dart:65:24)
[        ] E/flutter ( 4348): <asynchronous suspension>
[        ] E/flutter ( 4348): #10     Classifier._loadModel (package:tflite_flutter_plugin_example/classifier.dart:24:38)
[        ] E/flutter ( 4348): #11     new Classifier (package:tflite_flutter_plugin_example/classifier.dart:19:5)
[        ] E/flutter ( 4348): #12     _MyAppState.initState (package:tflite_flutter_plugin_example/main.dart:19:19)
[        ] E/flutter ( 4348): #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
[   +1 ms] E/flutter ( 4348): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
[   +4 ms] E/flutter ( 4348): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
[        ] E/flutter ( 4348): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
[        ] E/flutter ( 4348): #17     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
[        ] E/flutter ( 4348): #18     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
[        ] E/flutter ( 4348): #19     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17)
[        ] E/flutter ( 4348): #20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
[        ] E/flutter ( 4348): #21     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:941:13)
[   +4 ms] E/flutter ( 4348): #22     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:819:7)
[        ] E/flutter ( 4348): #23     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:804:7)
[        ] E/flutter ( 4348): #24     _rootRun (dart:async/zone.dart:1122:38)
[        ] E/flutter ( 4348): #25     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] E/flutter ( 4348): #26     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
[        ] E/flutter ( 4348): #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
[        ] E/flutter ( 4348): #28     _rootRun (dart:async/zone.dart:1126:13)
[        ] E/flutter ( 4348): #29     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] E/flutter ( 4348): #30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
[   +1 ms] E/flutter ( 4348): #31     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
[   +3 ms] E/flutter ( 4348): #32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
[        ] E/flutter ( 4348): #33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
[        ] E/flutter ( 4348): #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by kame5** [comment]
![image](https://user-images.githubusercontent.com/48491704/79685602-2f4ae780-8264-11ea-8269-180427e49616.png)
still can't execute 
>sh install.sh

Did I do something wrong?

**Comment by am15h** [comment]
Oh, I see you are a windows user. sh is for UNIX based system and cannot be directly run on windows, I will add a batch script in repo to support automatic intial setup for windows as well. 

I have now added the binaries to the example itself through latest commit to avoid inital setup for example. You can now try to clone the repo once again(or git pull) and it should work fine.

**Comment by kame5** [comment]
Thank you for your help, @am15h.
Finally, it works.

![image](https://user-images.githubusercontent.com/48491704/79713271-864dcc80-82f7-11ea-9f42-b9ebf95d3229.png)
