### ISSUE TITLE
the size of a one screen app is 65mb  what is that!!!

### ISSUE THREAD

**Issue by mohamed3051215** [am15h/tflite_flutter_plugin#150]

**Comment by jealvin** [comment]
You need to exclude lib that you do not need on your project inside app/build.gradle
`android {

    // some other code 

    buildTypes {
        release {
            // some other code 

            aaptOptions {
                ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:'
            }
        }
        debug {
            // some other code 

            aaptOptions {
                ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:'
            }
        }
    }

    packagingOptions {
        exclude 'lib/**/libtranslate_jni.so'
        exclude 'lib/**/libdigitalink.so'
        exclude 'lib/**/libxeno_native.so'
        exclude 'lib/**/libmlkitcommonpipeline.so'
        exclude 'lib/**/libbarhopper_v2.so' // required for Barcode
        exclude 'lib/**/libclassifier_jni.so'
        exclude 'lib/**/libface_detector_v2_jni.so' // required for face detector
        exclude 'lib/**/libtensorflowlite_jni.so'
        // exclude 'lib/**/liblanguage_id_jni.so' // required for language detection example comment
    }`
comment the line code, lib that used in project by using   "//"

**Comment by Fethi1** [comment]
yeah i was just gonna mention that, my app is that large suddenly

**Comment by Sid911** [comment]
@mohamed3051215 @Fethi1 have you tried to remove the x86 and related binaries from your application build?

**Comment by Fethi1** [comment]
No i didn't, wouldn't that effect the app ?

**Comment by Sid911** [comment]
@Fethi1 x86 and x86_64 binaries are not required if you are only building for mobile.
Usually people remove these using abi filters in release to reduce application size.

**Comment by jealvin** [comment]
can you run this code and share the json file?
`flutter build apk --analyze-size --target-platform=android-arm64`
Specify one of android-arm, android-arm64, or android-x64 in the --target-platform flag.

**Comment by Fethi1** [comment]
@Sid911 a link to an article or documentation would be highly appreciated

@jealvin I'll try that out

**Comment by Sid911** [comment]
@Fethi1 https://developer.android.com/ndk/guides/abis#gc that's the filter part but the entire introduction is a good read.

**Comment by am15h** [comment]
Thanks guys for pointing this out. The plugin itself doesn't affects the app size, if depends on the size of your `.tflite` model file and in general flutter apps are larger in size than native android apps. The best we can do is building carefully for each architecture so that only relevant binaries are included in build. I will add some documentation regarding this too.
