### ISSUE TITLE
NOT issue but question.

### ISSUE THREAD

**Issue by kamil-bit** [am15h/tflite_flutter_plugin#151]
Is possible in the future the configuration of app will be made automatically ?

**Comment by khue3012** [comment]
I got the error "TensorFlowLiteC framework not found" even though I copied this to the ios folder of the plugin in .pub-cache. How did you get through this OP?

**Comment by CaptainDario** [comment]
@khue3012 did you try running `dart pub get` like #141 suggests?

**Comment by khue3012** [comment]
@CaptainDario Yes. I ran that command so the plugin folder showed up. I copied the TensorflowLiteC.framework folder into the ios folder in the plugin folder. But it didn't work.

**Comment by khue3012** [comment]
Do I need to manually link something by using Xcode?

**Comment by CaptainDario** [comment]
@khue3012 I didn't need to link something with xcode. I ran
```
Dart pub get 
Flutter pub get
Pod install
```
And than copied the tensorflow lite framework into the tflite_flutter directory (both the dart and flutter directory)
Than it worked.

**Comment by khue3012** [comment]
Thank you for your quick response. I will try it. 
Have a nice day man.

**Comment by CaptainDario** [comment]
@khue3012 I had a lot of problems getting this pulgin working (on iOS, on android it was a painless process).
I think if we find a stable solution to this, it would benefit everybody.

For me it is now working but the MetalDelegate always throws an exepction #152 . So maybe my setup is also not correct.

**Comment by khue3012** [comment]
Yes. I think this plugin is great but it lacks some instructions for people who don't have lots of experience with native iOS/Android.

**Comment by am15h** [comment]
Thanks for your suggestions @CaptainDario and @khue3012, I will work on updating the documentation, especially on the iOS side.
