### ISSUE TITLE
tflite_flutter_helper problem

### ISSUE THREAD

**Issue by innerk** [am15h/tflite_flutter_plugin#162]
hi i'm having this problem the plugin helper 

tflite_flutter_helper >=0.2.2 depends on camera ^0.8.1+3 and aikrops depends on camera ^0.9.4+5, tflite_flutter_helper >=0.2.2 is forbidden.

**Comment by innerk** [comment]
@jmtrutna hi, the solution for me was downgrade the camera plugin 

  camera: ^0.8.1+3
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.0
  
  and in build gradle i change this
  
   compileSdkVersion 30
   targetSdkVersion 30
  
  at the moment my app is fully functional with image recognition from camera and image selection

**Comment by jmtrutna** [comment]
Thanks.  Downgrading the camera plugin works fine, however camera < 9.0 doesn't seem to have the controller.pausePreview() function which is helpful to me.

**Comment by jmtrutna** [comment]
Fixed in tflite_flutter_helper 0.3.1 !!
