### ISSUE TITLE
Desktop version support

### ISSUE THREAD

**Issue by abc873693** [am15h/tflite_flutter_plugin#17]
Have any plan for desktop(MacOS, Windows, Linux)?

**Comment by am15h** [comment]
Hi, @abc873693 You may try using https://github.com/dart-lang/tflite_native for desktop use cases. 
We might think of adding desktop support to this package as well in coming days.

**Comment by abc873693** [comment]
This plugin not support latest flutter FFI API.
May be fix it myself. Thanks you.

**Comment by am15h** [comment]
@abc873693 I didn't understand your concern. The plugin is using v0.1.3 which is the latest ffi version.

**Comment by abc873693** [comment]
Oh no. I got it wrong.
I will try it.

**Comment by CaptainDario** [comment]
As [the mentioned package](https://github.com/dart-lang/tflite_native) has been discontinued are there plans to support desktop?

**Comment by CaptainDario** [comment]
In the next month I will have some more time and would be interested in helping with this.
Is there already somebody working on it?

**Comment by am15h** [comment]
Thanks @CaptainDario for your interest. We will publish desktop support by early June.

**Comment by CaptainDario** [comment]
Thank you very much for this awesome plugin it enables so many possibilities.
