### ISSUE TITLE
[bug ?] Even in the Counter App, my Classifier / interpeter leaks memory after close()

### ISSUE THREAD

**Issue by espbee** [am15h/tflite_flutter_plugin#170]
I've run this (interpreter open / interpreter close) in the Flutter Counter App with nothing else happening. All it does is open and close the interpreter, like:

        Interpreter? interpreter;
        interpreter = await Interpreter.fromAsset(MODEL_FILE_NAME);
        interpreter?.close();

Or, the samde happens if I rely on the Classifier as in the example app.

Looking at the memory usage in XCode, after close, a chunk of the used memory does go away, but not all the way-- and then, crucially, the next time i open the interpreter, it goes up double. And the next time, tripple, roughly speaking. Each interpreter instance raises the amount risen. And each time, it drops down less. Before long the app crashes. I've tried this with my own custom tiny Yolo model and the SSD that goes with the example app from this lib. Same behavior. 

So the result, in terms of the memory graph, as i run, close, and re-run, etc, is like a step-pyramid that never goes back down. Like the model is failing to actually de-allocate and yet each time is re-alloacted. (I say the model specifically because my tiny Yolo model is slightly larger than the stock SSD model and the memory usage also is higher when I run with mine). 

**** Also, if I run the interpreter without adding a model, the rise does not happen.

So like this, more or less. Each rise is an interpreter opening, and the very small drop shortly after is the close. If I keep opening and closing, the rise continues until eventual crash.

<img width="1446" alt="Screen Shot 2022-01-22 at 4 01 40 PM" src="https://user-images.githubusercontent.com/67663740/150655506-5c16c99b-36d2-4875-8296-e3d18aac9a0e.png">

And here is the result if I use the Metal GPU delegate-- I'm not too concerned with this, the recognitions are fast enough without it, but for what it's worth, the memory usage is way more dramatic in this case:

<img width="1334" alt="Screen Shot 2022-01-22 at 4 04 57 PM" src="https://user-images.githubusercontent.com/67663740/150655573-e6823044-94b3-48c3-8d61-3048c9353962.png">

I keep thinking it could have something to do with Dart's garbage collection, but if no one is having this issue I'm at a loss for the moment. This happens on XCode 13 and also XCode 12.5. I haven't tried other versions. There's no appreciable change in the memory when I leave the route that handled the interpreter, even when all references should be null.

I've stumbled onto various TensorFlowLite / ios leak issues in the TF Github issues page and around the web... there definitely seems to be the potential for trouble. 

Does anyone have any sense of -- if I'm missing something really obvious? Or have any idea about what might be happening, or some route to explore, even, that I could delve into?

Or are all of you just opening the interpreter once and leaving it there until the app closes? 

I appreciate any help--

**Comment by espbee** [comment]
Note-- to be clear there's no inference being run or anything else, it's literally just opening and closing the interpreter;

& there is still an address after I close the interpreter, and it still prints as allocated, though also as deleted. 

If I wrap the intenral delete function in a try catch I don't catch anything. The memory does drop a good deal, just not all the way.

**Comment by jmtrutna** [comment]
Any updates?

**Comment by espbee** [comment]
@jmtrutna Not yet. I've been training a TinyYolo version of my model because... generally I prob should have done that to begin with, just to keep app size down. While it trains I've been working on other stuff. Tomorrow I'm back to this though. I'm concerned about it but no answers yet.

**Comment by espbee** [comment]
@jmtrutna have you looked at the XCode memory usage? Are you not experiencing this?

**Comment by espbee** [comment]
I think I may have solved it. Still running tests but it looks very promising. The key was loading the model from File rather than from the Asset bundle directly. It really seems like when you let the interpreter draw from an asset-bundle byte stream directly it's not ever letting go all the way. I hoped that by controlling the asset -> file myself and then handing off the local file to the interpreter that it might release, and it *loooks* so far like it is. 

Leaving this open for a sec till I confirm-- if anyone has had any similar experiences to any of this, I'd love to hear about it.

**Comment by espbee** [comment]
It does seems good now. Loading from file rather than asset was the key.

**Comment by jmtrutna** [comment]
How did you load your model from File? As of now I can only load and unload a dozen times.  

  /// Loads interpreter from asset
  void loadModel({Interpreter? interpreter}) async {
    try {
      _interpreter = interpreter ??
          await Interpreter.fromAsset(
            MODEL_FILE_NAME,
            options: InterpreterOptions()..threads = numThreads, //myOptions,
          );
      // print('numThreads: $numThreads');

      var outputTensors = _interpreter!.getOutputTensors();
      // print("the length of the output Tensors is ${outputTensors.length}");
      _outputShapes = [];
      _outputTypes = [];
      outputTensors.forEach((tensor) {
        //print(tensor.toString());
        _outputShapes!.add(tensor.shape);
        _outputTypes!.add(tensor.type);
      });
      print('YOLOv4Tiny model Loaded!');
    } catch (e) {
      print("Error while creating interpreter: $e");
    }
  }


 So you changed to Interpreter.fromFile()...  Sorry for the dumb question... but how did you reference your tflite file in your assets folder?

**Comment by app-chain-hagio** [comment]
> I think I may have solved it. Still running tests but it looks very promising. The key (perhaps): loading the model from File rather than from the Asset bundle directly. It really seems like when you let the interpreter draw from an asset-bundle byte stream directly it's not ever letting go all the way. I hoped that by controlling the asset -> file myself and then handing off the local file to the interpreter that it might release, and it _looks_ so far like it is.
> 
> Leaving this open till I confirm-- if anyone has had any similar experiences to any of this, I'd love to hear about it.


I've been having trouble with tflite's memory leak for a week now. I never thought it was a problem with the loading path. It was very helpful. thank you!
