### ISSUE TITLE
framework not found TensorFlowLiteC IOS

### ISSUE THREAD

**Issue by YFrendo** [am15h/tflite_flutter_plugin#171]
Hy everyone!
I can't find why the flutter build ios (and ipa) doesn't work. The Android version work like a charm.

The TensorFlowLiteC.framework folder is corectly place inside:
` /Users/<me>/.pub-cache/hosted/pub.dartlang.org/tflite_flutter-0.9.0/ios`

My flutter doctor is ok too but when I try to build it stop at Xcode build with:
framework not found TensorFlowLiteC

Thanks!

**Comment by espbee** [comment]
@YFrendo go into your app's ios folder, then the .symlinks folder, then the folder for this lib, then the ios folder, and place it there. You may have some issues running on the simulator versus a live device. If so, there are answers around the web, or I can help, if it arises--

**Comment by YFrendo** [comment]
Thanks @espbee !

I finaly managed to fix it with Xcode.
If someone want to know:
- Open Xcode on your ios folder
- Grab your framework and put it inside Pods/Framework
- Add it inside tflite_flutter
That's it 

Thanks!

**Comment by YFrendo** [comment]
Thanks @espbee !

It work with the flutter command (and I don't need more) but do you know why it still doesn't work on Xcode ?

**Comment by espbee** [comment]
What error are you getting? (I'm no XCode / ios expert but am learning as I go).

**Comment by YFrendo** [comment]
Nevermind it work now without any changement (probably the restart is enough)!
Thanks for your help!
This should be in the readme!
