### ISSUE TITLE
How Do I load my model from a file instead of an asset?

### ISSUE THREAD

**Issue by jmtrutna** [am15h/tflite_flutter_plugin#173]
I think I may have solved it. Still running tests but it looks very promising. The key (perhaps): loading the model from File rather than from the Asset bundle directly. It really seems like when you let the interpreter draw from an asset-bundle byte stream directly it's not ever letting go all the way. I hoped that by controlling the asset -> file myself and then handing off the local file to the interpreter that it might release, and it *looks* so far like it is. 

Leaving this open till I confirm-- if anyone has had any similar experiences to any of this, I'd love to hear about it.

_Originally posted by @espbee in https://github.com/am15h/tflite_flutter_plugin/issues/170#issuecomment-1019370216_

**Comment by jmtrutna** [comment]
@espbee seems to have solved a memory leak issue by loading his model from file instead of from asset.  How do I reference my model as a file instead?  Below is the current load model:

 /// Loads interpreter from asset
  void loadModel({Interpreter? interpreter}) async {
    try {
      _interpreter = interpreter ??
          await Interpreter.fromAsset(
            MODEL_FILE_NAME,
            options: InterpreterOptions()..threads = numThreads, //myOptions,
          );

I assume I just call interpreter.fromFile()...  but I don't know how to call my model

**Comment by saad-palapa** [comment]
```
final file = File(_modelPath);
_interpreter = Interpreter.fromFile(file, options: options);
```

**Comment by jmtrutna** [comment]
Thanks.

And I apologize for not reading carefully, but there is an example in the package. Example:

final dataFile = await getFile('assets/your_model.tflite');
final interpreter = Interpreter.fromFile(dataFile);

Future  getFile(String fileName) async {
  final appDir = await getTemporaryDirectory();
  final appPath = appDir.path;
  final fileOnDevice = File('$appPath/$fileName');
  final rawAssetFile = await rootBundle.load(fileName);
  final rawBytes = rawAssetFile.buffer.asUint8List(); -- note: I changed this to float32 to match my model...
  await fileOnDevice.writeAsBytes(rawBytes, flush: true);
  return fileOnDevice;

However I am getting an error "2 positional argument(s) expected, but 1 found" in File('$appPath/$fileName');
and
I'm also getting an error "The method 'writeAsBytes' isn't defined for the type 'File'" in await fileOnDevice.writeAsBytes(rawBytes, flush: true);

**Comment by jmtrutna** [comment]
I imported 'dart:html' instad of 'dart:io' which fixed those errors, however when I changed the rawAssetFile.buffer.asFloat32List(); I get the error for rawBytes: "The argument type 'Float32List' can't be assigned to the parameter type 'List<int>'". 

I also get the error:
flutter: Error while creating interpreter: FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/5A53AB70-14B7-4FDA-AE27-23A49BF0E72C/Library/Caches/assets/custom-416.tflite' (OS Error: No such file or directory, errno = 2)

**Comment by programmer-huda123** [comment]
hi @jmtrutna , does the code work with you ? 
I mean when you loading your custom model ..

**Comment by jmtrutna** [comment]
@programmer-huda123 I responded to you under your question.  My question still remains.  The argument type 'Float32List' can't be assigned to the parameter type 'List<int>' is my error when trying to load my model as a File.  I changed asUint8List() to asFloat32List() and I don't totally understand what that means, except that I know my model is of type Float32.  Code is below and I get the error in await fileOnDevice.writeAsBytes(rawBytes2, flush: true);

      Future<File> getFile(String fileName) async {
        final appDir = await getTemporaryDirectory();
        final appPath = appDir.path;
        final fileOnDevice = File('$appPath/$fileName');
        final rawAssetFile = await rootBundle.load(fileName);
        // final rawBytes = rawAssetFile.buffer.asUint8List();
        final rawBytes2 = rawAssetFile.buffer.asFloat32List();

        // await fileOnDevice.writeAsBytes(rawBytes, flush: true);
        await fileOnDevice.writeAsBytes(rawBytes2, flush: true);
        return fileOnDevice;
      }

      final dataFile = await getFile(MODEL_FILE_NAME);
      _interpreter = Interpreter.fromFile(
        dataFile,
        options: InterpreterOptions()..threads = numThreads,
      );

**Comment by niveen-n106** [comment]
oops 😥, so your app is nor working well ? or yeah ! , if yes can you give your repo link ? of course if there is no problem :)

**Comment by programmer-huda123** [comment]
oops 😥, so your app is nor working well ? or yeah ! , if yes can you give your repo link ? of course if there is no problem :)

**Comment by jmtrutna** [comment]
So my bad.  I got side tracked thinking uint8 vs float32 was the issue.  really it was putting 'assets/' before filename lol...
anyways it appears the memory leak is fixed.  props to @espbee for figuring out that loading from file instead of asset was a solution.
