### ISSUE TITLE
Unsupported data type 14 in tensor

### ISSUE THREAD

**Issue by AngelUrq** [am15h/tflite_flutter_plugin#178]
Hi, I was trying to run a custom TF model in my Flutter app. The first error I got at `_interpreter = await Interpreter.fromAsset('models/model.tflite');` was:

> E/tflite  ( 3271): Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
> E/tflite  ( 3271): Node number 5 (FlexTensorListReserve) failed to prepare.
> E/flutter ( 3271): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: failed precondition

Following the advice in #101 I downloaded the flex binaries, getting a new error:

> Initialized TensorFlow Lite runtime.
> E/tflite  ( 4289): Unsupported data type 14 in tensor 
> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Unable to create interpreter.

This is how I created my model:
```
i = keras.layers.Input(shape=(None, 4))
x = keras.layers.SimpleRNN(25, return_sequences=True)(i)
x = keras.layers.SimpleRNN(25)(x)
out1 = keras.layers.Dense(15, activation='softmax')(x)
out2 = keras.layers.Dense(15, activation='softmax')(x)

model = Model(inputs=i, outputs=[out1, out2])
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
```
Save it as TFLite model:

```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

tflite_model = converter.convert()

with open('model.tflite', 'wb') as f:
  f.write(tflite_model)
```

I also added the dependencies to build.gradle

```
dependencies {
        implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
        // This dependency adds the necessary TF op support.
        implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'
    }
```

Thanks for your help in advance!

**Comment by bobbylush02** [comment]
Hi, I was wondering if you have resolved this issue and remember how you fixed it. I'm encountering the exact same error message regarding flex delegate and am not sure how to resolve it. If you can provide any assistance it'd be much appreciated.

**Comment by AngelUrq** [comment]
@bobbylush02 sorry for the late answer, I'll leave my solution in case anyone else needs it.
The problem was related to Tensorflow version, I trained and deployed my model using TF 2.8 but the TF Lite Flutter binaries were for 2.5. I just downgraded and trained the model again.

**Comment by AntoineChauviere** [comment]
Hi, thanks for your info. Does it work on emulator?
