### ISSUE TITLE
can't load my custom model 

### ISSUE THREAD

**Issue by programmer-huda123** [am15h/tflite_flutter_plugin#186]
I am using TexMexMax's code to make detector app .. first, my dataset is only 1400 image and just one class.. I'm trained my model on yolo v5m "although the accuracy is not good enough :( " .. however, I tried to make like TexMexMax's code and tried to alter image_conversions.dart in tflite_flutter_helper 0.3.1 plugin but I get errors about this plugin ..
can you help me please ? I have no much time :(
I hope you can reply as soon as possible ..

**Comment by programmer-huda123** [comment]
**That is what I get when I run my app :** 

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tflite_flutter_helper-0.3.1/lib/src/image/image_conversions.dart:19:17: 
Error: Member not found: 'TensorImage.checkImageTensorShape'.
    TensorImage.checkImageTensorShape(shape);
                ^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tflite_flutter_helper-0.3.1/lib/src/image/image_conversions.dart:88:29: 
Error: Can't use the default List constructor.
Try using List.filled instead.
      List<int> rgbValues = List(h * w * 3);
                            ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tflite_flutter_helper-0.3.1/lib/src/image/color_space_type.dart:164:12: 
Error: The getter 'ImageConversions' isn't defined for the class '_RGB'.
 - '_RGB' is from 'package:tflite_flutter_helper/src/image/color_space_type.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tflite_flutter_helper-0.3.1/lib/src/image/color_space_type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ImageConversions'.
    return ImageConversions.convertRgbTensorBufferToImage(buffer);
           ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tflite_flutter_helper-0.3.1/lib/src/image/color_space_type.dart:204:12: 
Error: The getter 'ImageConversions' isn't defined for the class '_GRAYSCALE'.
 - '_GRAYSCALE' is from 'package:tflite_flutter_helper/src/image/color_space_type.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tflite_flutter_helper-0.3.1/lib/src/image/color_space_type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ImageConversions'.
    return ImageConversions.convertGrayscaleTensorBufferToImage(buffer);
           ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tflite_flutter_helper-0.3.1/lib/src/image/image_container.dart:45:5: Error: The getter 'ImageConversions' isn't defined for the class 'ImageContainer'.
 - 'ImageContainer' is from 'package:tflite_flutter_helper/src/image/image_container.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tflite_flutter_helper-0.3.1/lib/src/image/image_container.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ImageConversions'.
    ImageConversions.convertImageToTensorBuffer(image, buffer);
    ^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s
Running Gradle task 'assembleDebug'...                             44.3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by jmtrutna** [comment]
I used TexMexMax's code to alter my tflite_flutter_helper as well.  I originally got an error.  My issue was the changes I made in the image_conversions.dart file created errors in the example folder in the tflite_flutter_helper package.  Just deleting the example folder in the  tflite_flutter_helper package did the trick for me.  So my recommendation would be to open the tflite_flutter_helper package and make sure that your alterations inside of the  image_conversions.dart didn't cause errors anywhere else.

**Comment by programmer-huda123** [comment]
Thank you for replying, I deleted example folder, but nothing is happen, I get the error above and I don't know where it cause errors anywhere else .. 
the errors seems that there is undefined function

**Comment by jmtrutna** [comment]
Is your model uint8 or float32?

**Comment by programmer-huda123** [comment]
I think unit8, How can I know for sure?

**Comment by jmtrutna** [comment]
Open your model in this site:

https://netron.app/

**Comment by programmer-huda123** [comment]
oops 😥, so your app is nor working well ? or yeah ! , if yes can you give your repo link ? of course if there is no problem :)

**Comment by programmer-huda123** [comment]
my model is float32, I'm sorry for the error.

**Comment by jmtrutna** [comment]
inside of classifier.dart and inside of your predict function.  Find where you define your inputImage.  
and put:

print(inputImage.tfLiteType);

My guess is that it will be uint8.  So change your inputImage to:

TensorImage inputImage = TensorImage(TfLiteType.float32);

**Comment by programmer-huda123** [comment]
Hi again, apologies for the lag, been a busy days .. so I'm testing the model that TexMexMax is attached in his repo (yolov4-416-fp32.tflite) it's float 32 and it's already written TensorImage inputImage = TensorImage(TfLiteType.float32); in the code ..
also I copied all files in the [https://github.com/TexMexMax/tflite_flutter_helper/tree/master/lib](url) ... it worked but unfortunately didn't return any bounding boxes :( ..

**Comment by jmtrutna** [comment]
No apologies necessary.  I had just been using my model on individual images and then processing the results for my purposes.  But I can say that I have gotten the bounding boxes to work on video, but with 2 issues.  1) It isn't working with the recognitionsNMS so I am getting lots of overlapping boxes just using the recognitions list, and 2) it isn't working when loading the model from file as apposed to asset.  (I had a memory leak when loading from asset).  I may look into trying to solve these issues, but let me know if you figure anything out.

**Comment by programmer-huda123** [comment]
I tried a lot but nothing work :( .. I want to get the bounding boxes whether they are overlapping or not, I also want to specify the location of the object, and this is the main objective ..
but how do you load your model ? 
and of course I will let you know if I figure anything out, and you too

**Comment by programmer-huda123** [comment]
Hi. I tried a lot of solution but nothing work, no bounding boxes appear , what may the problem be ?

**Comment by jmtrutna** [comment]
Is your model giving you good results?  My results are subpar.
