### ISSUE TITLE
How to use within an Isolate?

### ISSUE THREAD

**Issue by zeornelas** [am15h/tflite_flutter_plugin#21]
Hi,

Congrats for this plugin!

I've been doing some tests to pass my predict function to a separate thread using an Isolate.

My first approach was loading your plugin within an Isolate, but that's not possible as it requires the initialization of the Bindings.

The second approach was to pass the Interpreter to the Isolate, but that is also not possible. It only accepts primitive values, and the interpreter is a dart:ffi object.

Do you have any hints on how to accomplish such a task?

**Comment by zeornelas** [comment]
I've been reading about Isolate in Flutter, and apparently, it is not possible to load plugins inside an Isolate.

I was trying to do this is because I'm running a prediction that is taking on average 400ms. The main problem is that it takes a lot longer than native implementations (Java and Objective-C) and is also blocking the UI thread.

It seems that the only solution for this is having the plugin itself, creating a thread. Are you considering implementing threads on this plugin?

**Comment by am15h** [comment]
Thanks, @zeornelas, for reporting this.

I will have to do some research on my side to suggest a solution for using the interpreter with isolates. If there is some functionality that needs to be added to the plugin itself, it can surely be done with the next update. 



> The main problem is that it takes a lot longer than native implementations (Java and Objective-C).

The plugin uses ffi which is in beta, while on Android, JNI is being used for bindings, so it is possible that the performance will improve in these aspects with further updates of ffi itself.  Can you share the differences, if possible?

In the meantime, can you please try these and see if they help?

**Acceleration support offered by the plugin**

* Run on multiple threads

```
var interpreterOptions = InterpreterOptions()..threads = 2;
final interpreter = await Interpreter.fromAsset('your_model.tflite',
    options: interpreterOptions);
```

* NNAPI Delegate on Android

```
var interpreterOptions = InterpreterOptions()..useNnApiForAndroid = true;
final interpreter = await Interpreter.fromAsset('your_model.tflite',
    options: interpreterOptions);
```

* GPU Delegate V2 on Android

```
var interpreterOptions = InterpreterOptions()..addDelegate(GpuDelegateV2());
final interpreter = await Interpreter.fromAsset('your_model.tflite',
    options: interpreterOptions);
```

* Metal Delegate on iOS

```
var interpreterOptions = InterpreterOptions()..useMetalDelegateForIOS = true;
final interpreter = await Interpreter.fromAsset('your_model.tflite',
    options: interpreterOptions);
```

**Comment by zeornelas** [comment]
Yesterday, I did some tests with those options.
I've been only testing it on Android, and the GPU Delegate V2 did not work for me.

I did not notice differences by using either the threads parameter or the NNAPI delegate. On average, I'm getting the same results.

I'm using the following code:
```
stopwatch.start();
await Future(() => _interpreter.runForMultipleInputs(inputs, outputs));
stopwatch.stop();
print('flutter predicted time: ${stopwatch.elapsedMilliseconds}ms');
print('interpreter predicted time: ${_interpreter.lastNativeInferenceDurationMicroSeconds}');
```

The first print is printing on average 400ms, and the second is presenting values between 80-120ms. I can understand that the time from flutter should be slightly higher than the interpreter's one, but this difference is far from acceptable. Do you know the reason for this?

**Comment by am15h** [comment]
> The first print is printing on average 400ms, and the second is presenting values between 80-120ms. I can understand that the time from flutter should be slightly higher than the interpreter's one, but this difference is far from acceptable. Do you know the reason for this?

@zeornelas `_interpreter.lastNativeInferenceDurationMicroSeconds` gives the time when actual inference is happening. However, before and after that(actual inference) some internal pre-processing and post-processing has to be done, which also includes a bunch of ffi calls. So the difference is just a result of that. **You will observe a similar difference on native Android platform as well when using TFLite Java api**. However, it will be lower, depending on the differences in speeds of JNI and ffi, as well as some other factors. 

This difference should lower with further updates in ffi and the plugin itself.

**Comment by am15h** [comment]
Hi @zeornelas, 

> The second approach was to pass the Interpreter to the Isolate, but that is also not possible. It only accepts primitive values, and the interpreter is a dart:ffi object.

Yes, there is an open issue https://github.com/dart-lang/sdk/issues/37216 regarding this.
__
> My first approach was loading your plugin within an Isolate, but that's not possible as it requires the initialization of the Bindings.

Correct, using `Interpreter.fromAsset` it won't be possible, however, you can still load  <your_model>.tflite to a Uint8List list in the main thread, and then pass the 
`Uint8List modelBuffer` to the isolate. Now, create the interpreter within Isolate using `Interpreter.fromBuffer` constructor.

You will need to use the low-level isolate API to achieve this.

Here is a demonstration of how this can be done in the text_classification example,

The constructor for [`classifier.dart`](https://github.com/am15h/tflite_flutter_plugin/blob/master/example/lib/classifier.dart) will change like this, rest everything remains the same.

```
Classifier(Uint8List buffer, Map<String, int> dict) {
    _interpreter = Interpreter.fromBuffer(buffer);
    _dict = dict;
  }
```

```
import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:tflite_flutter_plugin_example/classifier.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _modelFile = 'text_classification.tflite';
  final _vocabFile = 'text_classification_vocab.txt';
  static Map<String, int> dictionary;
  static Uint8List interpreterBuffer;
  String sample =
      "What a waste of my time. The movie was bad. I have not seen such a stupid movie in my life.The story of movie was very bad";

  Isolate _isolate;
  ReceivePort _receivePort;

  // Load interpreter as buffer and dict map in main thread
  @override
  void didChangeDependencies() {
    if (dictionary == null) {
      rootBundle.loadString('assets/$_vocabFile').then((vocab) {
        var dict = <String, int>{};
        final vocabList = vocab.split('\n');
        for (var i = 0; i < vocabList.length; i++) {
          var entry = vocabList[i].trim().split(' ');
          dict[entry[0]] = int.parse(entry[1]);
        }
        dictionary = dict;
      }).catchError((e) {
        print('Error while loading dict: ${e.toString()}');
      });
    }
    if (interpreterBuffer == null) {
      rootBundle.load('assets/$_modelFile').then((rawAssetFile) {
        final rawBytes = rawAssetFile.buffer.asUint8List();
        interpreterBuffer = rawBytes;
      }).catchError((e) {
        print('Error while loading buffer: ${e.toString()}');
      });
    }
    super.didChangeDependencies();
  }

  void _startIsolate() async {
    _receivePort = ReceivePort();

    IsolateData isolateData = IsolateData(
        sample, interpreterBuffer, dictionary, _receivePort.sendPort);

    _isolate = await Isolate.spawn(
      _entryPoint,
      isolateData,
    );

    _receivePort.listen(_getPredictionCallback, onDone: () {
    });
  }

  // Call this to kill isolate
  void _stopIsolate() {
    if (_isolate != null) {
      _receivePort.close();
      _isolate.kill(priority: Isolate.immediate);
      _isolate = null;
    }
  }

  void _getPredictionCallback(dynamic messageFromIsolate) {
    print(messageFromIsolate);
  }

  // Entry point must be a static function
  static void _entryPoint(IsolateData isolateData) async {
    // Classifier gets created in the isolate
    Classifier classifier = Classifier(isolateData.buffer, isolateData.dict);
    List<double> result = classifier.classify(isolateData.rawText);

    // isolate sends the result back to the main thread
    isolateData.sendPort.send(result);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.orangeAccent,
          title: const Text('Text classification'),
        ),
        body: FlatButton(
          child: const Text('Classify'),
          onPressed: () {
            _startIsolate();
          },
        ),
      ),
    );
  }
}
```

IsolateData class bundles all the data we need to send to isolate
```
class IsolateData {
  IsolateData(this.rawText, this.buffer, this.dict, this.sendPort);
  String rawText;
  Uint8List buffer;
  Map<String, int> dict;
  SendPort sendPort;
}
```

Let me know if this resolves your issue. :-)

**Comment by zeornelas** [comment]
Yes, it helped solving it. Thank you!
Unfortunately the whole inference process takes too long using this method, but I managed to keep the UI thread running.

**Comment by saurabhkumar8112** [comment]
Since this plugin has been taken over by tensorflow team, they have made it possible to do isolate inferece
Pls see here : https://github.com/tensorflow/flutter-tflite/blob/main/example/image_classification_mobilenet/lib/helper/isolate_inference.dart
