### ISSUE TITLE
Slow input tensors preparing

### ISSUE THREAD

**Issue by bitk0der** [am15h/tflite_flutter_plugin#23]
Hello, first of all - thank you for that plugin!

It works perfectly, inference time is running near realtime image processing, but i found out that preparing input tensors takes a huge amount of time, ex. for shape **[1, 257, 257, 3]** its about **350ms** in release mode (inference running for **45-50ms**). Reshaping list by that shape for input -  taking about **60ms**.

This is the bottleneck in **runForMultipleInputs** method:
```dart
var inputTensors = getInputTensors();
    for (var i = 0; i < inputs.length; i++) {
      if (inputTensors[i].shape != (inputs[i] as List).shape) {
        resizeInputTensor(i, (inputs[i] as List).shape);
        allocateTensors();
        inputTensors = getInputTensors();
      }
      inputTensors[i].setTo(inputs[i]);
    }
```

**Comment by am15h** [comment]
Hi @bitk0der, thanks for reporting.

Some optimizations are introduced with `tflite_flutter: ^0.4.0`. We will try to improve more (if possible) with further updates.

**Comment by am15h** [comment]
Hello @bitk0der, The [TFLite Flutter Helper Library](https://github.com/am15h/tflite_flutter_helper) has been released. It makes working with such use-cases easy and efficient. Please check it out and the [Image Processing Demo App](https://github.com/am15h/tflite_flutter_helper/tree/master/example/image_classification).
