### ISSUE TITLE
Unhandled Exception: Bad state: failed precondition

### ISSUE THREAD

**Issue by xellDart** [am15h/tflite_flutter_plugin#29]
Hello, I am trying to use the mediapipe facemesh model, which is this in tfjs format, but I can't get it to work, I have no idea what I'm doing wrong, I'd appreciate any help, thanks

Model: https://github.com/google/mediapipe/tree/master/mediapipe/models#face-mesh
File: https://github.com/google/mediapipe/blob/master/mediapipe/models/face_landmark.tflite

Code: 

```
Future _loadModel() async {
    _interpreter = await Interpreter.fromAsset('models/face_landmark.tflite');
    print('Interpreter loaded successfully');
  }

 _onStream() async {
    final CameraDescription description =
        await ScannerUtils.getCamera(_direction);
    controller = CameraController(description, ResolutionPreset.ultraHigh,
        enableAudio: false);
    await controller.initialize();
    setState(() {});
    await controller.startImageStream((CameraImage img) async {
      if (!_isDetecting) {
        var input = img.planes.map((plane) {return plane.bytes;}).toList();
        int list0 = 0;
        var output = new Map<int, Object>.from({0: list0});
        _interpreter.runForMultipleInputs(input, output);

        print(output.toString());

        _isDetecting = false;
      }
    });
  }
```

Error:

`2020-07-10 18:59:50.076078-0500 Runner[24953:4058491] flutter: Interpreter loaded successfully
2020-07-10 18:59:50.683677-0500 Runner[24953:4058491] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Bad state: failed precondition
#0      ced (PXe:71)
#1      jca.Tkd (XYe:150)
#2      gca.Fkd (UYe:183)
#3      _ho._cxb.<anonymous closure> (DPe:68)
#4      _ho._cxb.<anonymous closure> (DPe:63)
#5      am.yjb.<anonymous closure> (HOe:412)
#6      _fma (tLe:1198)
#7      _qc.wza (tLe:1100)
#8      _qc.Bza (tLe:1005)
#9      _BufferingStreamSubscription._Pya (qLe:357)
#10     _Kb.Rza (qLe:611)
#11     _Nb.TBa (qLe:730)
#12     _Ib.RBa.<anonymous closure> (qLe:687)
#13     _ema (tLe:1182)
#14     _qc.vza (tLe:1093)
#15     _qc.Aza (tLe:997)
#16     _qc.Iza.<anonymous closure> (tLe:1037)
#17     _ema (tLe:1190)
#18     _qc.vza (tLe:1093)
#19     _qc.Aza (tLe:997)
#20     _qc.Iza.<anonymous closure> (tLe:1037)
#21     _Mla (oLe:41)
#22     _Nla (oLe:50)`

Outputs from model:

```
[
      {
        faceInViewConfidence: 1, // The probability of a face being present.
        boundingBox: { // The bounding box surrounding the face.
          topLeft: [232.28, 145.26],
          bottomRight: [449.75, 308.36],
        },
        mesh: [ // The 3D coordinates of each facial landmark.
          [92.07, 119.49, -17.54],
          [91.97, 102.52, -30.54],
          ...
        ],
        scaledMesh: [ // The 3D coordinates of each facial landmark, normalized.
          [322.32, 297.58, -17.54],
          [322.18, 263.95, -30.54]
        ],
        annotations: { // Semantic groupings of the `scaledMesh` coordinates.
          silhouette: [
            [326.19, 124.72, -3.82],
            [351.06, 126.30, -3.00],
            ...
          ],
          ...
        }
      }
    ]
```

Info: https://www.npmjs.com/package/@tensorflow-models/facemesh

UPDATE

I update my code to this:

```
try {
      Interpreter interpreter =
          await Interpreter.fromAsset("models/face_detection_front.tflite");

      var _inputShape = interpreter.getInputTensor(0).shape;
      var _outputShape = interpreter.getOutputTensor(0).shape;
      var _outputType = interpreter.getOutputTensor(0).type;

      ImageProcessor imageProcessor = ImageProcessorBuilder()
          .add(ResizeOp(
              _inputShape[1], _inputShape[2], ResizeMethod.NEAREST_NEIGHBOUR))
          .build();
      var file = File(
          (await picker.getImage(source: ImageSource.gallery, maxWidth: 560))
              .path);
      TensorImage tensorImage = TensorImage.fromFile(file);
      tensorImage = imageProcessor.process(tensorImage);

      var _outputBuffer =
          TensorBuffer.createFixedSize(_outputShape, _outputType);
      print(_outputShape.toString());
      interpreter.run(tensorImage.buffer, _outputBuffer.getBuffer());
      print(_outputBuffer);
    } catch (e) {
      print(e);
    }
```

But i always get 
flutter: Bad state: failed precondition

**Comment by am15h** [comment]
@xellDart This could be happening because of bad input to the interpreter. Are you sure that normalization is not required for the input image? Try adding NormalizeOp to the image processing pipeline with appropriate values. Have you tried to find out if the current values of `tensorImage.buffer.asUint8List()` are same as the expected ones?

**Comment by xellDart** [comment]
Thanks, already worked, I only have one more question...
I have this code in python:
```
regressors = interpreter.get_tensor(output_details[0]["index"])
classificators = interpreter.get_tensor(output_details[1]["index"])
```

And with your lib I can get this with

```
List<Tensor> tensors = _interpreter.getOutputTensors();
Tensor regressors = tensors[0];
Tensor classificators = tensors[1];
```

My question is, how i can get elements in tensor like this:
Python regressort tensor elements:
```
regressors: 
[ 3.4080482e-01  2.5098801e-02  2.8392452e+01 ... -5.0155647e+01
  4.7399345e+01  1.4660334e+01]
```

In dart i try with get data, but this return integers...
Thanks

**Comment by am15h** [comment]
The list of integers with length 57344 is the bytes representation of the float data (Uint8List).

**Comment by KiruthikaAdhi** [comment]
@xellDart @am15h 

how did you solve this issue? I am facing the same error, my code is as follows

    File imageFile = File(filePath);
    ImageProcessor imageProcessor = ImageProcessorBuilder()
        .add(ResizeOp(224, 224, ResizeMethod.NEAREST_NEIGHBOUR))
        .build();

// Create a TensorImage object from a File
    TensorImage tensorImage = TensorImage.fromFile(imageFile);

// Preprocess the image.
// The image for imageFile will be resized to (224, 224)
    tensorImage = imageProcessor.process(tensorImage);

    TensorImage outputImage = new TensorImage();
    TensorBuffer probabilityBuffer = TensorBuffer.createFixedSize(<int>[1, 1001], TfLiteType.uint8);
    Interpreter interpreter = await Interpreter.fromAsset("models/example.tflite");
    interpreter.run(tensorImage.buffer, probabilityBuffer.buffer);

The error is as follows:

 Unhandled Exception: Bad state: failed precondition
E/flutter ( 5476): #0      checkState (package:quiver/check.dart:71:5)
E/flutter ( 5476): #1      Tensor.setTo (package:tflite_flutter/src/tensor.dart:150:5)
E/flutter ( 5476): #2      Interpreter.runForMultipleInputs (package:tflite_flutter/src/interpreter.dart:194:33)
E/flutter ( 5476): #3      Interpreter.run (package:tflite_flutter/src/interpreter.dart:165:5)


I have edge detection model which takes an input image and gives an output image. How should I solve this?

**Comment by xellDart** [comment]
The problem in my case was that it did not correctly declare the outputs of my models, each model has different shapes of tensioners, I put a sample of my code at the end

js
```
TensorImage tensorImage = TensorImage.fromFile(file);
      tensorImage = _imageProcessor.process(tensorImage);

      TensorBuffer output0 = TensorBuffer.createFixedSize(
          _interpreter.getOutputTensor(0).shape,
          _interpreter.getOutputTensor(0).type);
      TensorBuffer output1 = TensorBuffer.createFixedSize(
          _interpreter.getOutputTensor(1).shape,
          _interpreter.getOutputTensor(1).type);

      Map<int, ByteBuffer> outputs = {0: output0.buffer, 1: output1.buffer};

      _interpreter.runForMultipleInputs([tensorImage.buffer], outputs);
      List<double> regression = output0.getDoubleList();
      List<double> classificators = output1.getDoubleList();

```

**Comment by am15h** [comment]
Hi, @KiruthikaAdhi. 

> TensorBuffer probabilityBuffer = TensorBuffer.createFixedSize(<int>[1, 1001], TfLiteType.uint8);

The type of this buffer should be `TfLiteType.float32` and not `TfLiteType.uint8`.

**More info:**

This issue occurs because:
1. You might not be using the input/output buffers of correct shape, type as required by the interpreter. Verify this using `interpreter.getInputTensors()` and `interpreter.getOutputTensors()`

2. Probably the values of input buffer are not the expected ones. Maybe you are forgetting to normalize your input. Try using [NormalizeOp](https://pub.dev/documentation/tflite_flutter_helper/latest/tflite_flutter_helper/NormalizeOp-class.html).

**Comment by KiruthikaAdhi** [comment]
@xellDart @am15h Solved the issue by modifiying the shape of input and output tensors. Thanks for the help!

**Comment by matheper** [comment]
The PR is already closed but I want to share my experience in case someone has the same problem.

I faced the same issue and after a long time debugging I noticed my model expects an image type `TfLiteType.float32` instead of `TfLiteType.uint8`.

If you load the image using the static method `fromImage`, it will create a TensorImage type `TfLiteType.uint8`.
```
// _inputImage type TfLiteType.uint8
_inputImage = TensorImage.fromImage(image);
```

You should create the TensorImage object and load your image using the `loadImage`:
```
// _inputImage type TfLiteType.float32
_inputImage = TensorImage(TfLiteType.float32); 
_inputImage.loadImage(image);
```

**Comment by aklingam7** [comment]
Just look at the example repo here: https://github.com/am15h/tflite_flutter_helper/tree/master/example/image_classification

**Comment by CheerfulMinions** [comment]
> @xellDart @am15h Solved the issue by modifiying the shape of input and output tensors. Thanks for the help!

So do I,
add
```
...
_inputImage = TensorImage(_inputType);
_inputImage.loadImage(image);
```

**Comment by rj76** [comment]
Hi all,

Sorry to still respond on this closed ticket, but I'm running into this while using TfLiteType.float32

The code that I'm trying is at:

https://github.com/TexMexMax/object_detection_flutter/blob/master/lib/tflite/classifierYolov4.dart#L246

Does anybody have an idea?

cheers

**Comment by cahyowhy** [comment]
this is my `_interpreter.getInputTensors()`
```
[Tensor{_tensor: Pointer: address=0xb4000072a21f3030, name: serving_default_images:0, type: uint8, shape: [1, 320, 320, 3], data: 307200}]
```
iam using both
```
_inputImage = TensorImage.fromImage(image);
```
```
_inputImage = TensorImage(TfLiteType.float32); 
_inputImage.loadImage(image);
```

and still got an issue 😭 
need help
