### ISSUE TITLE
install.bat and install.sh have inaccessable download URL in them 

### ISSUE THREAD

**Issue by yoobter** [am15h/tflite_flutter_plugin#32]
Hi, thanks for your awesome plugin.  I wanted to let you know that I was able to find the binaries from an older version of the project, however you should be made aware that the download URL listed in the install.bat and install.sh files is not currently publicly accessable (i.e. "set URL=https://github.com/am15h/tflite_flutter_plugin/releases/download/" displays a gitHub 404 screen).  As mentioned, the work-around is easy enough, but I figured that you might want to know about this issue and adjust accordingly.  Thanks.

**Comment by am15h** [comment]
Thanks @yoobter. The above URL takes the form of https://github.com/am15h/tflite_flutter_plugin/releases/download/v0.2.0/libtensorflowlite_c_arm_delegate.so to download binaries.  The scripts install.sh and install.bat are working. Please feel to reopen if you wanted to point out something else. Thanks!

**Comment by yoobter** [comment]
Yes I see that you are correct (and I now see that I did not use the formula from below).  Apologies for the false report.  Thanks again.
