### ISSUE TITLE
Failed to load tensorflowlib when firebase_admob is used 

### ISSUE THREAD

**Issue by manmahani** [am15h/tflite_flutter_plugin#33]
I really appreciate your nice library that eases the usage of TF.

I am developing a mobile app for android and I am using tflite_flutter for some image processing tasks. Everything was fine until I added firebase_admob to my project. 
It seems that initiating the firebase_admob prevents tflite_flutter from loading the tensorflow lib!

Here is the runtime error I get: 
ArgumentError (Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libtensorflowlite_c.so" not found))
If I initiate firebase_admob in advance, like this:
FirebaseAdMob.instance.initialize(appId: "APP ID");

By disabling the firebase_admob  tflite_flutter works fine. I am not sure if the problem is with firebase_admob or tflite_flutter, but I came across a similar issue for libsqlite:
https://github.com/simolus3/moor/issues/420
According to the link, it seems that ffi is the root of problem.

I could reproduce the error with two versions if tflite_flutter lib: tflite_flutter: ^0.1.3, and tflite_flutter: ^0.5.0

Here is also the flutter doctor results:
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.14.5 18F203, locale en-DE)
    • Flutter version 1.17.3 at /Users/q416892/Documents/tt/flutter
    • Framework revision b041144f83 (7 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/q416892/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.0.2 (API 21) (emulator)

! Doctor found issues in 1 category.

Thanks in advance.

**Comment by manmahani** [comment]
The same error (dlopen failed: library "libtensorflowlite_c.so" not found) happens if I use facebook_audience_network, version 0.6.2. This time the error happens even if I just add the facebook_audience_network pubspec.yaml and even not using it in the code!

**Comment by manmahani** [comment]
The error is not there in release mode on a real device!

**Comment by am15h** [comment]
Thanks, @manmahani for reporting this. Good to see that you found a solution. I would investigate this further. 
Please feel free to share if you have any other queries.
