### ISSUE TITLE
NoSuchMethodError: The method 'run' was called on null even though install.bat is run

### ISSUE THREAD

**Issue by farazk86** [am15h/tflite_flutter_plugin#36]
Hi,

I'm teaching myself how to use tflite in dart using your awesome library, but I am having trouble making a basic example work.

I am trying to use ``DeepLabv3`` model to segment an image. I am following your provided example as a guide. Below is my code for a simple process in order to see what the output will be like.

```dart
class SegmentImage{
  Interpreter interpreter;
  InterpreterOptions _interpreterOptions;
  List<int> _inputShape;
  List<int> _outputShape;
  String modelName = 'deeplabv3_257_mv_gpu.tflite';

  TensorImage _inputImage;
  TensorBuffer _outputBuffer;

  // from example code, apparently this is how I call the NormalizeOp function
  NormalizeOp get preProcessNormalizeOp => NormalizeOp(127.5, 127.5);

  TfLiteType _outputType = TfLiteType.uint8;

  Future<void> loadModel() async {
    try {
      final interpreter = await Interpreter.fromAsset(modelName);
      print('Interpreter Created Successfully');

      _inputShape = interpreter.getInputTensor(0).shape;    // [1, 257, 257, 3]
      print('input_shape:');
      print(_inputShape);
      print(interpreter.getInputTensor(0).type);    //TfLiteType.float32
      _outputShape = interpreter.getOutputTensor(0).shape;
      print('output_shape:');
      print(_outputShape);
      _outputType = interpreter.getOutputTensor(0).type;
      print(_outputType);

      _outputBuffer = TensorBuffer.createFixedSize(_outputShape, _outputType);

    } catch (e) {
      print('Unable to create interpreter, Caught Exception: ${e.toString()}');
    }
  }

  Future<void> predict(File image) async{
    //read the image as bytes for TensorImage
    img.Image imageInput = img.decodeImage(image.readAsBytesSync());
    //this will be the tensor that will be used for prediction
    _inputImage = TensorImage.fromImage(imageInput);
    _inputImage = _preProcess();
    interpreter.run(_inputImage.buffer, _outputBuffer.getBuffer());
    print('output buffer shape and type');
    print(_outputBuffer.getShape());
    print(_outputBuffer.getDataType());
  }

  TensorImage _preProcess() {
    int cropSize = min(_inputImage.height, _inputImage.width);
    return ImageProcessorBuilder()
        .add(ResizeWithCropOrPadOp(cropSize, cropSize))
        .add(ResizeOp(
        _inputShape[1], _inputShape[2], ResizeMethod.NEAREST_NEIGHBOUR))
        .add(preProcessNormalizeOp)
        .build()
        .process(_inputImage);
  }

}
```

and this is my ``getImage()`` function that calls all the above:

```dart
  Future getImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.gallery);
    _image = File(pickedFile.path);
    await segmentImage.loadModel();
    await segmentImage.predict(_image);
```

But I am getting this error on ``run``:

```
E/flutter (15207): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'run' was called on null.
E/flutter (15207): Receiver: null
E/flutter (15207): Tried calling: run(Instance of '_ByteBuffer', Instance of '_ByteBuffer')
E/flutter (15207): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (15207): #1      SegmentImage.predict (package:easy_bg_changer/main.dart:102:17)
E/flutter (15207): #2      _HomePageState.getImage (package:easy_bg_changer/main.dart:37:24)
E/flutter (15207): <asynchronous suspension>
E/flutter (15207): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter (15207): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter (15207): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter (15207): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter (15207): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (15207): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
E/flutter (15207): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
E/flutter (15207): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
E/flutter (15207): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (15207): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (15207): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (15207): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (15207): #15     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (15207): #16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (15207): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (15207): #18     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter (15207): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
E/flutter (15207): 
```

I have seen this closed issue: https://github.com/am15h/tflite_flutter_plugin/issues/15 and I have run the ``install.bat`` script. If I run it again it asks me if I want to overwrite said files.. So the files have been installed.

What am I doing wrong?

P.S. An additional though after reading this issue on your other library: https://github.com/am15h/tflite_flutter_helper/issues/15, are image outputs not yet supported? 

Thanks

**Comment by am15h** [comment]
Hi @farazk86, Sorry for being late.  I think the issue here is that you are not calling `loadModel()`  method before calling `run`.

> P.S. An additional though after reading this issue on your other library: am15h/tflite_flutter_helper#15, are image outputs not yet supported?

I have provided the code to deal with image outputs in comments https://github.com/am15h/tflite_flutter_helper/issues/15#issuecomment-675596435. It will be integrated into the library soon. 

Thanks, please feel to comment below if you have any other queries.

**Comment by farazk86** [comment]
> Hi @farazk86, Sorry for being late. I think the issue here is that you are not calling `loadModel()` method before calling `run`.
> 
> > P.S. An additional though after reading this issue on your other library: [am15h/tflite_flutter_helper#15](https://github.com/am15h/tflite_flutter_helper/issues/15), are image outputs not yet supported?
> 
> I have provided the code to deal with image outputs in comments [am15h/tflite_flutter_helper#15 (comment)](https://github.com/am15h/tflite_flutter_helper/issues/15#issuecomment-675596435). It will be integrated into the library soon.
> 
> Thanks, please feel to comment below if you have any other queries.

Hi @am15h ,

Thanks for replying. 
I did load the model before running ``run``. Here is the function that is called on ``onPressed``

```dart
Future getImage() async {
    final pickedFile = await picker.getImage(source: ImageSource.gallery);
    _image = File(pickedFile.path);
    await segmentImage.loadModel();
    await segmentImage.predict(_image);
  }
```

**Comment by am15h** [comment]
Oh sorry my bad, took a closer look now. 

`final interpreter = await Interpreter.fromAsset(modelName);`

Remove `final` keyword. It is shadowing the class variable.

**Comment by farazk86** [comment]
Thank you, that fixed it.

I'll close this issue now as the purpose of this has been answered. :)

But I also want to ask another thing so as not to open a separate issue for it.

While waiting for your response, I searched around for an alternative and found  firebase local interpreter and ``modelManager``. My knowledge is this is still very limited but wanted to ask you about what is the difference between firebase interpreter and your library? Is there any benefit to use one over the other? I know that your library is better than the other ``tflite`` library for plugin as yours gives more flexibility and we can use the tf models as intended, but is it any different than firebase implementation?

Below is from my readings, just as an example, I have not implemented this in my code: But this is how firebase version of local interpreter is supposed to work.

Sorry if this is a very obvious answer question 

```
import 'package:mlkit/mlkit.dart';

FirebaseModelInterpreter interpreter = FirebaseModelInterpreter.instance;
FirebaseModelManager manager = FirebaseModelManager.instance;

manager.registerLocalModelSource(
    FirebaseLocalModelSource(
        assetFilePath: "assets/models/plant_ai_lite_model.tflite",
        modelName: "plant_ai_model"
    )
);
//     rootBundle.loadString('assets/models/labels_plant_ai.txt').then((string) {
    var _labels = string.split('\n');
    _labels.removeLast();
    modelLabels = _labels;
});
```

Thank you
