### ISSUE TITLE
Usage of deprecated API

### ISSUE THREAD

**Issue by mselmanyildirim** [am15h/tflite_flutter_plugin#37]
Hi,
Thanks for your valuable efforts.
Recently Android Studio complains about your package, saying:
`Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\tflite_flutter-0.5.0\android\src\main\java\com\tfliteflutter\tflite_flutter_plugin\TfliteFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.`
I think this won't cause an issue soon, but you may consider improving it for better support in the future.

**Comment by am15h** [comment]
@mselmanyildirim Thanks for pointing out will be fixed in a future update if possible.

**Comment by am15h** [comment]
Fixed with the latest update.
