### ISSUE TITLE
sh install.sh error

### ISSUE THREAD

**Issue by dijorajsenroy** [am15h/tflite_flutter_plugin#42]
used flutter pub get to download the package, but some how the TensorImage class cannot be used. So I copied and ran the bash file in project root but it gives errors:

readlink: illegal option -- f
usage: readlink [-n] [file ...]
install.sh: line 29: wget: command not found
mv: rename libtensorflowlite_c_arm.so to android/app/src/main/jniLibs/armeabi-v7a/libtensorflowlite_c.so: No such file or directory
install.sh: line 29: wget: command not found
mv: rename libtensorflowlite_c_arm64.so to android/app/src/main/jniLibs/arm64-v8a/libtensorflowlite_c.so: No such file or directory
install.sh: line 29: wget: command not found
mv: rename libtensorflowlite_c_x86.so to android/app/src/main/jniLibs/x86/libtensorflowlite_c.so: No such file or directory
install.sh: line 29: wget: command not found
mv: rename libtensorflowlite_c_x86_64.so to android/app/src/main/jniLibs/x86_64/libtensorflowlite_c.so: No such file or directory``

**Comment by wolfgio** [comment]
same problem here

**Comment by am15h** [comment]
@dijorajsenroy @wolfgio 
wget command is not installed properly on your linux machines, 
Firstly try to install them
'sudo apt-get install wget'
Then run the script.

If you are in windows then follow instructions to use 'install.bat'

**Comment by wolfgio** [comment]
That did the trick here! thanks
btw if you are a macos user you can install wget with homebrew

**Comment by tazsid** [comment]
After trying `install wget` and `sh install.sh` it is till giving the error:
```
: command not found 
readlink: illegal option -- f
usage: readlink [-n] [file ...]
: No such file or directory
: command not found 
: command not found 
: command not found: 
: command not found: 
: command not found: 
'nstall.sh: line 22: syntax error near unexpected token `in
'nstall.sh: line 22: `  case $OPTION in
```

**Comment by MATTYGILO** [comment]
> That did the trick here! thanks
> btw if you are a macos user you can install wget with homebrew

brew install wget

**Comment by dunghacknicktao** [comment]
> After trying `install wget` and `sh install.sh` it is till giving the error:
> 
> ```
> : command not found 
> readlink: illegal option -- f
> usage: readlink [-n] [file ...]
> : No such file or directory
> : command not found 
> : command not found 
> : command not found: 
> : command not found: 
> : command not found: 
> 'nstall.sh: line 22: syntax error near unexpected token `in
> 'nstall.sh: line 22: `  case $OPTION in
> ```

same problem :(
