### ISSUE TITLE
Is this using the latest stable tensorflow version?

### ISSUE THREAD

**Issue by left-brain** [am15h/tflite_flutter_plugin#47]
Looks like the plugin is using TFLite C API version 2.2 is this correct? The latest stable tensorflow version is 2.3.1, can you please update the .so files?

**Comment by left-brain** [comment]
Please help me with that, I’m training my model on Tensorflow 2.3.0 and I’m getting errors because the library is 2.2

**Comment by am15h** [comment]
@left-brain You can get the tf 2.3.1 binaries from https://github.com/am15h/tflite_flutter_plugin/releases/tag/v0.5.0, I will update the install scripts as well.

**Comment by left-brain** [comment]
It worked, thanks :)
