### ISSUE TITLE
Failed to lookup symbol (undefined symbol: TfLiteGpuDelegateV2Create)

### ISSUE THREAD

**Issue by left-brain** [am15h/tflite_flutter_plugin#49]
When I try to run the model with GpuDelegate I receive this error:

Unhandled Exception: Invalid argument(s): Failed to lookup symbol (undefined symbol: TfLiteGpuDelegateV2Create).

I searched that on the internet and looks like it's a problem with the ffi.

**Comment by am15h** [comment]
@left-brain Can you please confirm if you are using binaries with delegate build, i,e. libtensorflowlite_c_arm64_delegate.so or libtensorflowlite_c_arm_delegate.so from [here](https://github.com/am15h/tflite_flutter_plugin/releases/tag/v0.5.0)

**Comment by left-brain** [comment]
No, I am not! Thanks for the help!! I’ll check it out :)

**Comment by am15h** [comment]
Closing this issue. Please feel free to reopen if you face any other problems.

**Comment by jaweii** [comment]
how to check if you are using binaries with delegate build?
