### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by biernacki** [am15h/tflite_flutter_plugin#5]
Hi, very nice effort! My team is also using bindings from `tflite_native` package in Flutter, but your additions to this package are very interesting. Could you add a License so we could evaluate if we can use it and possibly contribute to it?

**Comment by am15h** [comment]
Thanks, @biernacki for the feedback, we are in the process of wrapping up things for the first version and expecting to publish it on pub.dev next week. I will try to add a license as soon as possible, after discussing it with my mentors from the TensorFlow team.

**Comment by am15h** [comment]
Hi, This project is now licensed under the Apache License 2.0. Closing this issue.
