### ISSUE TITLE
Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'

### ISSUE THREAD

**Issue by SergioSanchezMontesUAM** [am15h/tflite_flutter_plugin#50]
While trying to create an `Interpreter` from an asset the following error is caught:

```
E/tflite  (24363): Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'
E/tflite  (24363): Registration failed.
I/flutter (24363): Error while creating interpreter: Invalid argument(s): Unable to create interpreter.
```

The asset is a custom [YOLO](https://github.com/ultralytics/yolov5) model exported to TFLite using these [instructions](https://github.com/ultralytics/yolov5/pull/1127). 
It has 1 input `float32[1,640,640,3]` and 3 outputs `float32[1,3,6400,85]`, `float32[1,3,1600,85]` and `float32[1,3,400,85]`

**Comment by joonlabs** [comment]
take a look at #53 that should solve your problem

**Comment by Sreyas-108** [comment]
I am facing this same issue trace on android with a custom built model. Upgrading to v0.5.0 didnt help.

**Comment by am15h** [comment]
@Sreyas-108 Can you please sharing if you are on Android, or iOS?

**Comment by KingWu** [comment]
How to solve this problem. Upgrade to 0.9.0. Didn't help
