### ISSUE TITLE
Unable to loading a Custom TFlite Model 

### ISSUE THREAD

**Issue by mlopez0** [am15h/tflite_flutter_plugin#52]
I follow along this [Colab](https://colab.research.google.com/drive/1qXn9q6m5ug7EWJsJov6mHaotHhCUY-wG?usp=sharing)  to  train a custom model.

[Conversion process Colab](https://colab.research.google.com/drive/1VRH4K_LPXlTv-YvobWjvxOAowxTYIli8?usp=sharing) 

After completing the training process I converted the .pb to .tflite and I got [these files](https://drive.google.com/drive/folders/1I8pU34M9gagLFdImmrpS8qUY6Wge0jds?usp=sharing). When I loaded the model into the [official Android demo](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android)  I got the following error:

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sd_detect/com.example.sd_detect.MainActivity}: java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.
```
The solution to that error is discussed in [this issue](https://github.com/tensorflow/tensorflow/issues/44431)

I followed the solution:

Installing the metadata library with:
```
pip install tflite-support

```
and then executing the following command into python
```
>>> from tflite_support import metadata as _metadata
>>> populator = _metadata.MetadataPopulator.with_model_file('final_model.tflite')
>>> populator.load_associated_files(["final_model.txt"])
>>> populator.populate() 
```

And I got the following warning:

    /home/username/.local/lib/python3.8/site-packages/tensorflow_lite_support/metadata/python/metadata.py:342: UserWarning: File, 'final_model.txt', does not exsit in the metadata. But packing it to tflite model is still allowed.
      warnings.warn(

Back to Android Studio example I was able to run the model successfully, by just modifying this information:

    private static final String TF_OD_API_MODEL_FILE = "final_model.tflite";  
    private static final boolean IS_MODEL_QUANTIZED = false;
    private static final String TF_OD_API_LABELS_FILE = "final_model.txt";  

But when I bring my model to my Flutter application, I got the following exeption:

    /// Throws a [StateError] if the given [expression] is `false`.
    
    void  checkState(bool expression, {message}) {
    
    if (!expression) {
    
    throw  StateError(_resolveMessage(message, 'failed precondition'));
    
    }
    
    }
The flutter [project](https://github.com/am15h/object_detection_flutter) is fully working with coco_ssd_mobilenet_v1_1.0_quant_2018_06_29

I also tried to re-run the metadata commands on my flutter application assets but still the same issue.

What am I missing?

Edited:
In Android Studio (Android App) I set the variable IS_MODEL_QUANTIZED to false, is the issue related to this?

**Comment by am15h** [comment]
Hi @mlopez0, Can you share the exact error log, also can you double check that you are using the same .tflite file in both your Android and Flutter versions.

**Comment by mlopez0** [comment]
Thanks for the fast response @am15h, I really appreciate your time and effort!

Yes, I'm using the same [final_model.tfilte](https://drive.google.com/drive/folders/1I8pU34M9gagLFdImmrpS8qUY6Wge0jds?usp=sharing), in both projects.

When I do  `flutter run -v` I just got this 
```

[ +106 ms] I/CameraManagerGlobal( 5945): Connecting to camera service
[ +649 ms] W/Gralloc4( 5945): allocator 3.x is not supported
[ +358 ms] I/tflite  ( 5945): Initialized TensorFlow Lite runtime.
[ +887 ms] E/flutter ( 5945): [ERROR:flutter/runtime/dart_isolate.cc(988)] Unhandled exception:
[        ] E/flutter ( 5945): Bad state: failed precondition
[        ] E/flutter ( 5945): #0      checkState (package:quiver/check.dart:71:5)
[   +4 ms] E/flutter ( 5945): #1      Tensor.setTo (package:tflite_flutter/src/tensor.dart:150:5)
[        ] E/flutter ( 5945): #2      Interpreter.runForMultipleInputs (package:tflite_flutter/src/interpreter.dart:194:33)
[        ] E/flutter ( 5945): #3      Classifier.predict (package:object_detection/tflite/classifier.dart:137:18)
[        ] E/flutter ( 5945): #4      IsolateUtils.entryPoint (package:object_detection/utils/isolate_utils.dart:45:51)
[        ] E/flutter ( 5945): <asynchronous suspension>
[+1344 ms] W/System  ( 5945): A resource failed to call release. 
[+2014 ms] I/bject_detectio( 5945): Background concurrent copying GC freed 574(82KB) AllocSpace objects, 24(1840KB) LOS objects, 49% free, 3388KB/6777KB, paused 33us total 146.714ms
[+2678 ms] I/bject_detectio( 5945): Background concurrent copying GC freed 721(82KB) AllocSpace objects, 27(1956KB) LOS objects, 49% free, 4341KB/8683KB, paused 30us total 426.004ms
```

The app keep running with no detection.

The only modification I did to the project was in the  `classifier.dart` file line 20 & 21 

    static  const  String  MODEL_FILE_NAME = "final_model.tflite";
    static  const  String  LABEL_FILE_NAME = "final_model.txt";

Here's also a screenshot when I debug the application, with the exception I mentioned in my previous message.
![debug_screenshot](https://user-images.githubusercontent.com/54511822/100868334-88daec00-34ac-11eb-86b2-f788316bdaea.png)

Thanks for the support!

**Comment by piyushchauhan** [comment]
I am facing the same error.
```
I/flutter ( 8266): Caught error: Unable to load asset: assets/assets/efficientnet-lite3/efficientnet-lite3-fp32.tflite, while trying to load asset from "assets/assets/efficientnet-lite3/efficientnet-lite3-fp32.tflite"
I/flutter ( 8266): Caught error: NoSuchMethodError: The getter 'buffer' was called on null.
I/flutter ( 8266): Receiver: null
I/flutter ( 8266): Tried calling: buffer, while trying to create interpreter from asset: assets/efficientnet-lite3/efficientnet-lite3-fp32.tflite
E/flutter ( 8266): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null.
E/flutter ( 8266): Receiver: null
E/flutter ( 8266): Tried calling: length
E/flutter ( 8266): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 8266): #1      new Model.fromBuffer
package:tflite_flutter/src/model.dart:32
E/flutter ( 8266): #2      new Interpreter.fromBuffer
package:tflite_flutter/src/interpreter.dart:90
E/flutter ( 8266): #3      Interpreter.fromAsset
package:tflite_flutter/src/interpreter.dart:114
E/flutter ( 8266): <asynchronous suspension>
E/flutter ( 8266): #4      _ImagePageState.build.<anonymous closure>

```

**Comment by am15h** [comment]
> I/flutter ( 8266): Caught error: Unable to load asset: assets/assets/efficientnet-lite3/efficientnet-lite3-fp32.tflite, while trying to load asset from "assets/assets/efficientnet-lite3/efficientnet-lite3-fp32.tflite"

@piyushchauhan Can you please check if you have mentioned your asset in `pubspec.yaml` and the path is correct?

**Comment by mlopez0** [comment]
@am15h  Thanks for the fast response and support!

I read the thread multiples times to understand the problem, and discovered that you were right the type is incorrect.

**My custom model**

The output of `var inputT = _interpreter.getInputTensors();` is: 

```
[Tensor{
    _tensor: Pointer<TfLiteTensor>: address=0x7db8063b80, 
    name: normalized_input_image_tensor, 
    type: TfLiteType.float32, 
    shape: [1, 300, 300, 3], 
    data:  1080000
]
```

and the output of `var outputT = _interpreter.getOutputTensors();` is:
```
[
Tensor{
    _tensor: Pointer<TfLiteTensor>: 
    address=0x7db8063800, 
    name: TFLite_Detection_PostProcess, 
    type: TfLiteType.float32, 
    shape: [1, 10, 4], 
    data:  160, 
Tensor{
    _tensor: Pointer<TfLiteTensor>: address=0x7db8063870, 
    name: TFLite_Detection_PostProcess:1, 
    type: TfLiteType.float32, 
    shape: [1, 10], 
    data:  40, 
Tensor{
    _tensor: Pointer<TfLiteTensor>: address=0x7db80638e0, 
    name: TFLite_Detection_PostProcess:2, 
    type: TfLiteType.float32, 
    shape: [1, 10], 
    data:  40, 
Tensor{
    _tensor: Pointer<TfLiteTensor>: address=0x7db8063950, 
    name: TFLite_Detection_PostProcess:3, 
    type: TfLiteType.float32, 
    shape: [1], 
    data:  4
]
```

The difference are in the `data` and `type`, I'm sending a float32 and a [uint8](https://github.com/am15h/tflite_flutter_plugin/issues/29#issuecomment-656987629) is required.

I replaced the line [124](https://github.com/am15h/object_detection_flutter/blob/a5281e11b885a57e9ee2a2c7cc162a95554caed1/lib/tflite/classifier.dart#L124):

    List<Object> inputs = [inputImage.buffer];

with this one:

    List<Object> inputs = [inputImage.buffer.asUint8List()];

But I'm still getting the same error: `'failed precondition'`

Am I doing it right or do I need to replace something else?


Regading the NormalizeOp class, could you please clarify how to use it? the constructors takes two parameters: mean and stddev. Dumb question: where can I get these values?

**Comment by kietdinh** [comment]
Hi, I just face this problems. 

1. You need to make sure your input shape match the model shape.
2. NormalizeOP should place at the end of the builder to prevent error that create image from floating point.
3. Mean and Std you must set exactly when you train model. For example, mobilenet should be 127.5 and 127.5. If model is quant, they should be 0 and 255. You will get bad result if either mean or std are wrong.

**Comment by mlopez0** [comment]
Awesome setting the mean to 127.5 and stderr 127.5 solved my issue. 

Thanks for all the support and help @am15h @kietdinh

**Comment by ashugorthy** [comment]
> Awesome setting the mean to 127.5 and stderr 127.5 solved my issue.

@mlopez0 where do you set this?
