### ISSUE TITLE
Old iOS TFLite-Framework version - Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'

### ISSUE THREAD

**Issue by joonlabs** [am15h/tflite_flutter_plugin#53]
While running our tf-lite model on Android works perfectly, the model on iOS cannot be interpreted with the following error:
`Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'`

We're using an UpSamling Layer which uses that operation you can see above. 

I guess, the reason for that is, that the iOS-side of the plug-in does not contain the newest TFLite-Framework-C release, because the Tensorflow-Team released the RESIZE_NEAREST_NEIGHBOR operation just a few months ago.

Could this be fixed and the new version of the TFLite-Framework for iOS be added in the near future?

Cheers :)

**Comment by joonlabs** [comment]
You can fix this issue for **android** by replacing the _v0.2.0_ version variable with _v0.5.0_ in the install.sh script to download the latest builds of tflite for android.
For **iOS** you can either compile tflite yourself on a Mac (currently only working on Intel-Macs) and place it into the _/ios/_-folder your local version of the plugin, or wait until a new version will be released, that includes the latest tflite build for iOS.

**Comment by am15h** [comment]
Thanks @joonlabs, I have updated the TAG in install-scripts.
