### ISSUE TITLE
How to improve latency of object detection model ssd_mobilenet_v3_small_coco?

### ISSUE THREAD

**Issue by FelixBruebach** [am15h/tflite_flutter_plugin#58]
First of all thanks for this awesome plugin!

I am using this plugin to do interference with the model 'ssd_mobilenet_v3_small_coco' which can be found [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md).

This is how I invoke the interpreter:

`interpreter.runForMultipleInputs( [input], {0: output1, 1: output2, 2: output3, 3: output4} );`

I get good predictions, but interference takes longer than expected. According to the [model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md)  'ssd_mobilenet_v3_small_coco' needs 43ms on a Pixel 1. I am testing on a One Plus 7 Pro where it takes ~250ms (without delegates). Shouldn't I be able to achieve similiar if not better latency, because the One Plus should have better processing units or does the Pixel 1 have some kind of special processing unit which enables faster interference?

When I try to use

`var interpreterOptions = InterpreterOptions()..useNnApiForAndroid = true;`

I get the error

`I/TypeManager(13204): Failed to read /vendor/etc/nnapi_extensions_app_allowlist ; No app allowlisted for vendor extensions use.`

and interference takes around 2 seconds.

Using

```
    final gpuDelegateV2 = GpuDelegateV2(
        options: GpuDelegateOptionsV2(
          true,
          TfLiteGpuInferenceUsage.fastSingleAnswer,
          TfLiteGpuInferencePriority.minLatency,
          TfLiteGpuInferencePriority.minLatency,
          TfLiteGpuInferencePriority.minLatency,
        ));
```

does not improve the latency.

Is there anything I can do to improve the latency?

**Comment by am15h** [comment]
Hi @FelixBruebach, The NNAPI error might be related to the model or device-specific configuration. I will need to dig into that. However, it doesn't seem to be related to the plugin directly.  

> According to the model zoo 'ssd_mobilenet_v3_small_coco' needs 43ms on a Pixel 1.`

Can you share what configuration was used for benchmarking here?

**You can try changing the number of threads to 4 and see if that improves the performance.**

```dart
var interpreter = await Interpreter.fromAsset(
            MODEL_FILE_NAME,
            options: InterpreterOptions()..threads = 4,
          );
```

**Comment by FelixBruebach** [comment]
Thanks for the fast response @am15h!

I am not quite sure what you mean by configuration.

Since I did not do the benchmark myself I can only assume that the latency of 43ms corresponds to the model which you can download in the model zoo by clicking the name of the model ([ssd_mobilenet_v3_large_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_small_coco_2020_01_14.tar.gz)). It is quantized and has an input shape of (1, 320, 320, 3). I cannot find more information regarding the benchmark in the model zoo, but in the [paper](https://arxiv.org/pdf/1905.02244v5.pdf) which introduced this model there is a graph that shows the speed of the model, but with an input shape of (1, 224, 224, 3) on Pixel 1 using a single large core and tflite.

![Screenshot_1](https://user-images.githubusercontent.com/41200990/102382731-0cc3c680-3fcb-11eb-8fa6-958126fe9c42.png)
 
I tried different numbers of threads and it sadly didn't improve the latency.

My trained models are currently not quantized. When I tried to do interference with the unchanged model from the model zoo in order to see how much of a difference quantization makes, but I had problems, because the dtype uint8 is not supported by the plugin while int8 is. Is this intended?

**Comment by FelixBruebach** [comment]
I found out that interference takes 14ms with my model which is great.

`(interpreter.lastNativeInferenceDurationMicroSeconds / 1000).round(); // 14ms`

But invoking the method `runForMultipleInputs` takes around 303ms.

```
    interpreter.runForMultipleInputs(
      [input],
      {0: output1, 1: output2, 2: output3, 3: output4},
    ); // 303ms
```

The reasons is that the `4D-List of doubles` I am passing to the method gets converted to a `Uint8List` before interference which takes 286ms.

```
  void setTo(Object src) {
    var bytes = _convertObjectToBytes(src); // 286ms
    var size = bytes.length;
    ...
```

I can bypass this issue by converting the 4D-List to bytes before passing it to `runForMultipleInputs`. 😄 

However I think it should be possible to improve `_convertObjectToBytes`. Maybe by flattening the input if it is a list one time for each of its dimensions, wrap it in the desired TypedDataList and convert it to UInt8List. At least that is how I preprocess my input  to bypass the overhead that is generated by `_convertObjectToBytes`.

If you (@am15h) don't approve you can close this issue.

Again thanks for this awesome plugin!
