### ISSUE TITLE
Making sense of outputs from runForMultipleInputs

### ISSUE THREAD

**Issue by mgalgs** [am15h/tflite_flutter_plugin#59]
First, thank you for the excellent library!

I'm trying to get a custom object detection model working in Flutter and I feel like I'm right on the finish line but the outputs aren't really making sense. I'm not sure if I'm messing up my usage of your library or if I made a mistake earlier (in training or something) so let me know if I should post this to SO or file an issue somewhere else. I am able to use my custom model under full Tensorflow using the Python bindings so I _think_ my model is good...

Summary:

- All model training and exporting done using tf nightly (`2.5.0-dev20201215`).
- Built my own tflite shared objects so that I could get the latest Tensorflow lite. ([Docker-based build environment from the tf repo](https://github.com/tensorflow/tensorflow/blob/39d6ff7ac596950ef677271be7cfa44c95384ba9/tensorflow/lite/g3doc/guide/build_android.md#set-up-build-environment-using-docker), [build commands from this repo](https://github.com/am15h/tflite_flutter_plugin/blob/cb3e0d001ac8e670614a746017c5525532452238/README.md#use-the-plugin-with-any-tensorflow-version)).
- Custom trained model (based on [ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8.tar.gz)) using [`tensorflow/models/research/object_detection/model_main_tf2.py`](https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py) and [my pipeline.config](https://gist.github.com/mgalgs/4948b28a603077a4a3356b83bb6af128).
- Model exported using [`tensorflow/models/research/object_detection/exporter_main_v2.py`](https://github.com/tensorflow/models/blob/master/research/object_detection/exporter_main_v2.py) (same pipeline.config as in training).
- Model converted to tflite with [`convert_to_tflite.py`](https://gist.github.com/mgalgs/5f52115a859b9b07a7dfa5224f5a98a0).
- I can successfully detect objects using the regular Tensorflow Python bindings.
- Input and output shapes are shown in Figure A below. It seems a little strange that the height and width of the input tensor are `None` (which means "unknown" or "variable-sized" as per the [`tf.TensorShape` docs](https://www.tensorflow.org/api_docs/python/tf/TensorShape) and [a comment in the source](https://github.com/tensorflow/tensorflow/blob/582c8d236cb079023657287c318ff26adb239002/tensorflow/python/framework/tensor_shape.py#L766)), but maybe that's normal since it doesn't seem to stop the model from working on regular Tensorflow.

My "detect" method:

```dart
  detect(Image image) async {
    TensorImage timg = TensorImage.fromImage(image);
    timg = _preProcess(timg);

    _interpreter.runForMultipleInputs([timg.buffer], _outputBuffers);

    for (int i = 0; i < _outputTensorBuffers.length; i++) {
      TensorBuffer buffer = _outputTensorBuffers[i];
      print("${_outputTensorNames[i]}: ${buffer.getDoubleList()}");
    }
  }
```
(full source listing in Listing A below.)

results in the following output:

```
I/flutter (12516): StatefulPartitionedCall:5: [100.0]
I/flutter (12516): StatefulPartitionedCall:2: [5.0]
I/flutter (12516): StatefulPartitionedCall:7: [0.003288567066192627, 0.00007053170702420175, 0.00040328502655029297, 0.00022339820861816406, 0.0009590387344360352, 0.00682443380355835, 0.006241738796234131, 0.004405707120895386, 0.006697863340377808, 0.0030375123023986816, 0.0009462237358093262, 0.0014250576496124268, 0.0004329383373260498, 0.00403711199760437, 0.001086801290512085, 0.003039032220840454, 0.0006709098815917969, 0.003288090229034424, 0.0037768781185150146, 0.00008151835208991542, 0.0005600154399871826, 0.0005548596382141113, 0.0011392831802368164, 0.008495986461639404, 0.005149126052856445, 0.004283487796783447, 0.007070749998092651, 0.0038556158542633057, 0.00033274292945861816, 0.0002855658531188965, 0.000373154878616333, 0.0014458894729614258, 0.0006978213787078857, 0.0024288594722747803, 0.0006158053874969482, 0.0030787885189056396, 0.0032474100589752197, 0.0006365478038787842, 0.00037983059883117676, 0.0007419586181640625, 0.0025945305824279785, 0.0018936693668365479, 0.0027012526988983154, 0.00430268049240
I/flutter (12516): StatefulPartitionedCall:4: [0.03188779950141907]
I/flutter (12516): StatefulPartitionedCall:6: [-0.009938137605786324, -0.011441117152571678, 0.05219971388578415, 0.04861987382173538, -0.016602735966444016, -0.010687697678804398, 0.0830603837966919, 0.07274940609931946, -0.007124748080968857, -0.009804163128137589, 0.03815270960330963, 0.04826470836997032, -0.011091910302639008, -0.008176783099770546, 0.06167861819267273, 0.06926850229501724, -0.005919046700000763, -0.013556137681007385, 0.05681357532739639, 0.03645564243197441, -0.02163616754114628, -0.011458851397037506, 0.0747147724032402, 0.06488804519176483, -0.0017826557159423828, -0.02006278745830059, 0.08506569266319275, 0.07615071535110474, -0.016631372272968292, -0.019205741584300995, 0.13718745112419128, 0.0941062793135643, -0.012604944407939911, -0.009613707661628723, 0.06616833060979843, 0.0632333755493164, -0.01230534166097641, -0.006209280341863632, 0.10614445805549622, 0.07859446108341217, 0.016275424510240555, -0.02164752036333084, 0.07109864056110382, 0.07278952747583389, 0.003784455358982086, -0.0303153768
I/flutter (12516): StatefulPartitionedCall:3: [0.002476513385772705]
I/flutter (12516): StatefulPartitionedCall:1: [0.07430143654346466]
I/flutter (12516): StatefulPartitionedCall:0: [40274.0]
```

I've been unable to make sense of those outputs...

Any idea what I'm doing wrong here?

### Figure A: Input and Output Shapes

![image](https://user-images.githubusercontent.com/152014/102409066-4d0f4e80-3fa3-11eb-8b3e-38111f9335d9.png)

### Listing A: `object_detect.dart`

```dart
import 'dart:math';
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:tflite_flutter/tflite_flutter.dart';
import 'package:tflite_flutter_helper/tflite_flutter_helper.dart';
import 'package:image/image.dart';

class ObjectDetector {
  // should live in assets/. Don't include assets/ in the name.
  final String modelName;
  ObjectDetector(this.modelName);

  Interpreter _interpreter;
  List<int> _inputShape;
  Map<int, ByteBuffer> _outputBuffers = new Map<int, ByteBuffer>();
  Map<int, TensorBuffer> _outputTensorBuffers = new Map<int, TensorBuffer>();
  Map<int, String> _outputTensorNames = new Map<int, String>();

  initialize() async {
    _interpreter = await Interpreter.fromAsset(this.modelName);
    _inputShape = _interpreter.getInputTensor(0).shape;

    var outputTensors = _interpreter.getOutputTensors();

    outputTensors.asMap().forEach((i, tensor) {
      TensorBuffer output =
          TensorBuffer.createFixedSize(tensor.shape, tensor.type);
      _outputTensorBuffers[i] = output;
      _outputBuffers[i] = output.buffer;
      _outputTensorNames[i] = tensor.name;
    });
  }

  TensorImage _preProcess(TensorImage timg) {
    int cropSize = min(timg.height, timg.width);
    ImageProcessor processor = ImageProcessorBuilder()
        .add(ResizeWithCropOrPadOp(cropSize, cropSize))
        .add(ResizeOp(
        _inputShape[1], _inputShape[2], ResizeMethod.NEAREST_NEIGHBOUR))
        .add(NormalizeOp(0, 1))
        .build();
    return processor.process(timg);
  }

  detect(Image image) async {
    TensorImage timg = TensorImage.fromImage(image);
    timg = _preProcess(timg);

    _interpreter.runForMultipleInputs([timg.buffer], _outputBuffers);

    for (int i = 0; i < _outputTensorBuffers.length; i++) {
      TensorBuffer buffer = _outputTensorBuffers[i];
      print("${_outputTensorNames[i]}: ${buffer.getDoubleList()}");
    }
  }
}
```

**Comment by mgalgs** [comment]
Ok... Looking at some model documentation at [thub for the ssd_resnet_50_v1_fpn_640x640 model](https://tfhub.dev/tensorflow/retinanet/resnet50_v1_fpn_640x640/1), I think I need to sort out which output tensor is which and use the appropriate getter for each one (`.getIntList()` for the `num_detections` output, etc.) rather than using `.getDoubleList()` for everyone. I think I'm just missing how to determine which tensor from  corresponds to which output tensor is which... I've tried checking `tensor.name` but they're all named `"StatefulPartitionedCall:N"`... I also noticed that the output tensors all have `tensor.type == TfLiteType.float32` :thinking: Shouldn't they have different types depending on the output (int for `num_detections` and `detection_classes`, for example)?

**Comment by am15h** [comment]
Hi @mgalgs, did you checkout https://github.com/am15h/object_detection_flutter/blob/master/lib/tflite/classifier.dart, your usage looks quite similar to this one?

**Comment by mgalgs** [comment]
Hi @am15h yes I've been referencing that guy. The issue is this part where you map output buffers:

https://github.com/am15h/object_detection_flutter/blob/8186662c40d52f6a9198b7742dd7d02dcfbfa51d/lib/tflite/classifier.dart#L126-L132

It looks like you're using Mobilenet v1 in `object_detection_flutter`, so I've tried basing my custom model off of that. However, when I do:

```dart
var outputTensors = _interpreter.getOutputTensors();
```

I get _8_ output tensors:

![image](https://user-images.githubusercontent.com/152014/103237096-8036d380-48fb-11eb-8703-947906e61c3c.png)

and they're all named `Stateful PartitionedCall:N` and have type `float32`, and the data doesn't seem to correspond to my expected outputs.

I've also tried basing my model on Resnet50 and Mobilenet v2, all with the same result. I always have 8 outputs, even when I use Mobilenet v1 which, [according to thub](https://tfhub.dev/tensorflow/lite-model/ssd_mobilenet_v1/1/metadata/2), should only have 4 outputs (which is what you have in your code as well, so makes sense).

So I'm not sure what I'm doing wrong here that's resulting in me always getting 8 output tensors with funky names and data...

When I shove in [your model from `object_detection_flutter`](https://github.com/am15h/object_detection_flutter/tree/master/assets) I get 4 outputs and everything seems to be working as expected. So I'm not sure what I'm doing that's making my custom models have 8 outputs...

**Comment by mgalgs** [comment]
(I've updated my original post to use Mobilenet v1 to more closely match your `object_detection_flutter` example)

**Comment by mgalgs** [comment]
hmm ok if I also run my model through `object_detection/export_tflite_graph_tf2.py` as described in the [Running TF2 Detection API Models on mobile](https://github.com/tensorflow/models/blob/67fd2bef6500c14b95e0b0de846960ed13802405/research/object_detection/g3doc/running_on_mobile_tf2.md) docs in `tensorflow/models/research/object_detection` I get 4 output tensors, though they're still named differently from yours and all have a type of `float32`:

![image](https://user-images.githubusercontent.com/152014/103241009-cfcecc80-4906-11eb-9b52-d0a91c83bd8a.png)

However, now when I run inference I get the following failure:

```
E/flutter (24334): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: failed precondition
E/flutter (24334): #0      checkState (package:quiver/check.dart:73:5)
E/flutter (24334): #1      Tensor.setTo (package:tflite_flutter/src/tensor.dart:150:5)
E/flutter (24334): #2      Interpreter.runForMultipleInputs (package:tflite_flutter/src/interpreter.dart:194:33)
E/flutter (24334): #3      ObjectDetector.detect (package:routespotter/object_detect.dart:65:18)
E/flutter (24334): #4      _CameraState.startCameraStream.<anonymous closure> (package:routespotter/camera.dart:123:18)
E/flutter (24334): #5      CameraController.startImageStream.<anonymous closure> (package:camera/camera.dart:412:20)
E/flutter (24334): #6      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (24334): #7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (24334): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (24334): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (24334): #10     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (24334): #11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (24334): #12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (24334): #13     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (24334): #14     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (24334): #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (24334): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (24334): #17     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (24334): #18     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (24334): #19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (24334): #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (24334): #21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (24334): #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by mgalgs** [comment]
Um holy cow I may have cracked this nut! Changed my `TensorImage` to be `float32` based as per [this comment](https://github.com/am15h/tflite_flutter_plugin/issues/29#issuecomment-667596763) and now I'm getting seemingly valid results!

So summary of changes:

- I was missing the `export_tflite_graph_tf2.py` step. I had been doing the tflite conversion straight from my "regular" inference graph, rather than doing it against this new "tflite" inference graph.
- Use a `float32` `TensorImage`.

Thanks for taking a peek even though it doesn't look like there was any issue with your library!
