### ISSUE TITLE
ios: Failed to lookup symbol (dlsym(RTLD_DEFAULT, TfLiteGpuDelegateOptionsV2Default): symbol not found)

### ISSUE THREAD

**Issue by jaweii** [am15h/tflite_flutter_plugin#60]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

```
    final gpuDelegate = GpuDelegateV2();
    var interpreterOptions = InterpreterOptions()..addDelegate(gpuDelegate);
    interpreter = await Interpreter.fromAsset(
      'ml/yolov4-tiny-1280-final.tflite',
      options: interpreterOptions,
    );
```

HELP PLEASE!

**Comment by am15h** [comment]
Can you please try running `sh install.sh -d` at the root of your project. This should fix your problem.

**Comment by jaweii** [comment]
I have already run it and it is working.  I am running in the simulator on mac. Is this only working for Android?






------------------ Original ------------------

**Comment by am15h** [comment]
Hi @jaweii, for ios please try https://pub.dev/documentation/tflite_flutter/latest/tflite_flutter/GpuDelegate-class.html 
And
https://pub.dev/documentation/tflite_flutter/latest/tflite_flutter/GpuDelegateOptions-class.html

Or

https://pub.dev/documentation/tflite_flutter/latest/tflite_flutter/InterpreterOptions/useMetalDelegateForIOS.html

**Comment by am15h** [comment]
I am closing this issue, assuming that above resolution fixed your problem. Please feel free to reopen, if required.

**Comment by shaheer20** [comment]
@am15h  Having same issue i have tried both of your solutions but no luck.
