### ISSUE TITLE
How to perform inference in isolates?

### ISSUE THREAD

**Issue by farazk86** [am15h/tflite_flutter_plugin#62]
Hi,

In the key features its mentioned:

`- Run inference in different isolates to prevent jank in UI thread.`

But I am having trouble achieving this. And I cant find any example of this in documentation of examples. Can you please provide a very simple example of how this would work?

I have a very simple app, that runs inference on a list of ``int``. Since its a very small app, I'm doing everything in ``main.dart``.

The reason I am having trouble with isolates is because I initialize the ``Interpreter _interpreter`` in my main and then I cant pass this ``_interpreter`` to the isolate. As the isolate function has to be completely separate. I tried declaring the Interpreter globally above main, but that also didnt work.

I dont want to initialize the _interpreter in the isolate as that would load the model for every inference.

How would I call inference in isolate please?

Thanks

**Comment by am15h** [comment]
Please checkout the object detection example.

**Comment by farazk86** [comment]
> Please checkout the object detection example.

Thanks, but I can't find any object detection example. You have a text classification example [here ](https://github.com/am15h/tflite_flutter_plugin/tree/master/example)and an image classification example [here](https://github.com/am15h/tflite_flutter_helper/tree/master/example/image_classification).

**Comment by am15h** [comment]
Sorry, will update the readme with all the examples. https://github.com/am15h/object_detection_flutter
