### ISSUE TITLE
cant add my own teachablemachine.withgoogle.com models 

### ISSUE THREAD

**Issue by assanbayev** [am15h/tflite_flutter_plugin#65]
when i try to add my own model i have this error? what it might be?
`[ERROR:flutter/runtime/dart_isolate.cc(993)] Unhandled exception:
E/flutter ( 6540): RangeError (index): Invalid value: Only valid value is 0: 1
E/flutter ( 6540): #0      List.[] (dart:core-patch/growable_array.dart:183:60)
E/flutter ( 6540): #1      Classifier.predict (package:object_detection/tflite/classifier.dart:118:65)
E/flutter ( 6540): #2      IsolateUtils.entryPoint (package:object_detection/utils/isolate_utils.dart:45:51)`

**Comment by am15h** [comment]
@assanbayev Can you please share the reproducible code and corresponding error log. At first glance from what you have shared it looks like a local error with your code and might not be related to the plugin.

**Comment by am15h** [comment]
Closing this as the error doesn't seem to be due to the plugin, please feel to reopen if required.
