### ISSUE TITLE
How to get values from a model producing output of type int64?

### ISSUE THREAD

**Issue by farazk86** [am15h/tflite_flutter_plugin#72]
Hi,

I have a model with the following details:

```dart
var _inputShape = _interpreter.getInputTensor(0).shape;    //[256, 256]
    var _inputType = _interpreter.getInputTensor(0).type;    //float32
    _outputShape = _interpreter.getOutputTensor(0).shape;   //[256, 256]
    _outputType = _interpreter.getOutputTensor(0).type;    /// int64
```

I tried using ``tflite_flutter_helper`` package but cannot as I get the error: ``TensorBuffer does not support type int64``. So I am handling of input and output of my model as follows:

```dart
img.Image originalImage = img.decodeImage(File(imgFile.path).readAsBytesSync());
    img.Image imgResize = img.copyResize(originalImage, width:256, height:256);
    Uint8List inputImage = _imageToByteListUInt8(imgResize, 256, 0, 255);

    var predictions = List.filled(256, List.filled(256, 0));        // create empty list of size [256, 256] with 0 fill
    _interpreter.run(inputImage, predictions);

    img.Image outputMask = _convertArrayToImage(predictions, 256);
```

The helper functions used above are:

```dart
Uint8List _imageToByteListUInt8(
      img.Image image,
      int inputSize,
      double mean,
      double std,
      ) {
    var convertedBytes = Float32List(1 * inputSize * inputSize * 3);
    var buffer = Float32List.view(convertedBytes.buffer);
    int pixelIndex = 0;

    for (var i = 0; i < inputSize; i++) {
      for (var j = 0; j < inputSize; j++) {
        var pixel = image.getPixel(j, i);
        buffer[pixelIndex++] = (img.getRed(pixel) - mean) / std;
        buffer[pixelIndex++] = (img.getGreen(pixel) - mean) / std;
        buffer[pixelIndex++] = (img.getBlue(pixel) - mean) / std;
      }
    }
    return convertedBytes.buffer.asUint8List();
  }

```

The ``_interpreter`` runs but I cannot extract data from the ``predictions``. 

The model is a segmentation model and the output is color code for each detected region e.g. in Python the output from the interpreter is ``0=ground, 1=sky`` etc..

How do I extract this data from the predictions?

I tried to convert the output Array to ``image`` using:

```dart
img.Image _convertArrayToImage(List<List<int>> imageArray, int inputSize) {
    img.Image image = img.Image.rgb(inputSize, inputSize);
    for (var x = 0; x < imageArray.length; x++) {
      for (var y = 0; y < imageArray[0].length; y++) {
        var r = (imageArray[x][y]).toInt();
        var g = (imageArray[x][y+1]).toInt();
        var b = (imageArray[x][y+2]).toInt();
        var a = (imageArray[x][y+3]).toInt();
        image.setPixelRgba(x, y, r, g, b);
      }
    }
    return image;
  }
```
But I get the error: ``Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..255: 256`` And this error shows that my method for this is wrong, I dont want ``Uint8`` values, I want the int64 color codes..

Thanks

**Comment by haidar786** [comment]
@farazk86 Did you solve the issue? How you do that?

**Comment by farazk86** [comment]
> @farazk86 Did you solve the issue? How you do that?

I ended up solving this in java. It's quite simple actually, since the outputs were already ``int64`` I could just use them as is. For example I used below to iterate over the entire output of the tflite interpreter

```java
for (int y = 0; y < output[1].length; y++){
            for (int x = 0; x < output[0].length; x++){
                if (output[x][y] == 11){
                    // logic of what you want to do with this pixel
                }
            }
        }
```

I'm sure you can do the very same in dart. I used java because dart's image library is very old now and the creator himself says its not fit for purpose and very slow.
