### ISSUE TITLE
Recompile Binaries using flex delegates

### ISSUE THREAD

**Issue by henry8th** [am15h/tflite_flutter_plugin#75]
Hi,
If we need to use flex delegate with our models do I simply need to recompile with flex delegates option

bazel build -c opt --config=ios --ios_multi_cpus=armv7,arm64,x86_64 \
  //tensorflow/lite/ios:TensorFlowLiteSelectTfOps_framework

As such? Thank you

**Comment by am15h** [comment]
Sorry, FlexDelegate support is not available yet.

**Comment by am15h** [comment]
Developments will be tracked with https://github.com/am15h/tflite_flutter_plugin/issues/51.
