### ISSUE TITLE
Can't register quantized model compiled with tf-nightly (opcode error : 'CONV_2D' )

### ISSUE THREAD

**Issue by desdotl** [am15h/tflite_flutter_plugin#91]
I was testing toy model converted in tf-nightly version:2.5.0-dev20210314
I got the following error:

`E/tflite  (23791): Didn't find op for builtin opcode 'CONV_2D' version '5'
E/tflite  (23791): Registration failed.
E/flutter (23791): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Unable to create interpreter.`

Standing to a similar issue [here](https://github.com/tensorflow/tensorflow/issues/41943#issuecomment-700341312) in tflie (flutter package) the problem is related to the TFLite runtime and it states that the nightly version is required.
Can you help me?
What is the highest version supported in the libtensorflowlite_c_*.so files?

**Comment by desdotl** [comment]
Update: the problem is related to quantization, independently of the specific version (tested on tf 2.2 2.3 2.4.1)

**Comment by am15h** [comment]
> Update: the problem is related to quantization, independently of the specific version (tested on tf 2.2 2.3 2.4.1)

@desdotl are you able to get it work with non-quantized model?

**Comment by desdotl** [comment]
Yes with float32 format no problem

**Comment by am15h** [comment]
I think this issue is independent of this package and something related to tensorflow itself. I would suggest to [open an issue on tensorflow repository.](https://github.com/tensorflow/tensorflow/issues/new/choose).

**Comment by desdotl** [comment]
SOLVED
I've tried to update the version of the library locally in my project. I took the source from [this repository](https://github.com/ValYouW/tflite-dist) by @ValYouW for TensorFlow version 2.4.1 and now it works also for optimized version. I'm not sure if it can cause side effects but apparently, it's working fine.
