### ISSUE TITLE
Why to choose "tflite_flutter" and not "tflite"?

### ISSUE THREAD

**Issue by warcayac** [am15h/tflite_flutter_plugin#94]
Besides the fact that [tflite](https://pub.dev/packages/tflite) is outdated and does not require additional installations depending on the platform, what benefits does your package have compared to **tflite**? is it _Null-Safety_?

**Comment by am15h** [comment]
The [Key features listed in readme](https://github.com/am15h/tflite_flutter_plugin#key-features) are not possible to achieve with [tflite](https://pub.dev/packages/tflite). 

I have also address this in my [Text Classification Blog](https://medium.com/@am15hg/text-classification-using-tensorflow-lite-plugin-for-flutter-3b92f6655982)

> Q. How is this plugin tflite_flutter different from tflite v1.0.5
> While tflite v1.0.5 focuses on offering some high-level features to build apps with specific use cases like Image Classification, Object Detection, etc.., the new, tflite_flutter offers the same flexibility and features as the Java API and can be used with any tflite model. It also offers support for delegates.
> tflite_flutter is fast (has low latency) as it uses dart:ffi (dart ↔️(ffi) ↔️C) while tflite uses platform integration (dart ↔️platform-channel ↔️(Java/Swift) ↔️JNI ↔️C).

**Comment by yaizudamashii** [comment]
I can answer that question, having used both tflite and this package.  
First of all, this package is hard to use.  It has many shortcomings, like lack of PoseNet example or need to set the interpreter input yourself by preprocessing, getting the right buffer type (ints, floats, quantized, non quantized etc).  There are many places to get things wrong.  But the examples are written very well using using Dart isolates and it's very powerful that you can use any model.  This package is very powerful, just not for all use cases.

tflite on the other hand, is very easy to use, and it has good examples.  You can follow them, and you can get a somewhat working thing in a couple days or shorter.  But you have less flexibility, models used are couple years old... 

So there are pros and cons for both packages, respectively, and depending on what you are coding, you need to choose one.

BTW, unrelatedly, I found that Flutter's image resizing (desampling) is quite worse than that of iOS.  Even if you somehow use OpenCV using ffi (it took quite a bit of work, and didn't reliably work), the quality is still worse than iOS.  The order of quality in my opinion was
iOS > OpenCV > image package > ImageProcessor used in examples written by @am15h.  
So there is a lot for us to do, but the maintainer of this package has written good starting points.
