### ISSUE TITLE
Output error

### ISSUE THREAD

**Issue by Srikarthikeyan4006** [am15h/tflite_flutter_plugin#98]
Total elements mismatch expected: 1 elements for shape: [1, 1] but found 2

output decleration
var output = List<double>(2).reshape([1,1]);

**Comment by am15h** [comment]
@Srikarthikeyan4006 What is the target shape that you are trying to achieve? If your target shape is [a, b, c] then you should be doing. 
`var output = List(a*b*c).reshape([a, b, c]);`
