### ISSUE TITLE
How to change TensorFlow version for iOS?

### ISSUE THREAD

**Issue by applikationsprogramvara** [am15h/tflite_flutter_plugin#99]
I am using a model created for TFLite 2.3 and getting the error when running the app on iOS:
```
Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'
Registration failed.
```
I've managed to fix this error for Android by replacing *.so files from [release](https://github.com/am15h/tflite_flutter_plugin/releases/tag/v0.5.0) using `install` script as recommended in Readme.

But I can't figure out how to switch TFLite version for iOS. In Readme it is said, that the original API is dynamically linked as `TensorFlowLiteC.framework`. Should I update something there?

**Comment by applikationsprogramvara** [comment]
Ok. I've managed to start the model on iOS.

To do that I placed the updated [`TensorFlowLiteC.framework`](https://github.com/am15h/tflite_flutter_plugin/releases/download/v0.5.0/TensorFlowLiteC.framework.zip) to the directory `FLUTTER_DIR/.pub-cache/hosted/pub.dartlang.org/tflite_flutter-0.5.0/ios/TensorFlowLiteC.framework` (just replaced the directory).

I would suggest to add the way to update the framework to Readme or somehow automatise that with e.g. `install` script.

**Comment by am15h** [comment]
Let's track this here https://github.com/am15h/tflite_flutter_plugin/issues/110.
